### ISSUE TITLE
TMX corpus crash

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#211] opened 2017-01-06 13:52 UTC
I got an error one step before ...

I will dig what's wrong in my TMX (export from studio 2015).
But it would be good if the raised exception could be specific on what translation unit it crashes

INFO: (1 of 7) TMs clean-up...                                         DONE (in 21s)
ERROR Unexpected exception:
	Command 'java -cp /home/moses/ModernMT/build/mmt-0.14.jar -Dmmt.home=/home/moses/ModernMT -Djava.library.path=/home/moses/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s nl -t en --output /home/moses/ModernMT/runtime/nl-en-belgique/tmp/training/clean_tms --input /home/moses/ModernMT/data/nl_NL-en_UK' failed with exit code 1
Traceback (most recent call last):
  File "./mmt", line 583, in <module>
    main()
  File "./mmt", line 561, in main
    actions[command](args)
  File "./mmt", line 383, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/moses/ModernMT/cli/engine.py", line 193, in build
    unprocessed_bicorpora, self._get_tempdir('clean_tms')
  File "/home/moses/ModernMT/cli/mt/processing.py", line 96, in clean
    shell.execute(command, stdin=shell.DEVNULL, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/home/moses/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command 'java -cp /home/moses/ModernMT/build/mmt-0.14.jar -Dmmt.home=/home/moses/ModernMT -Djava.library.path=/home/moses/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s nl -t en --output /home/moses/ModernMT/runtime/nl-en-belgique/tmp/training/clean_tms --input /home/moses/ModernMT/data/nl_NL-en_UK' failed with exit code 1

**Comment by vince62s** [comment] 2017-01-06 14:15
ok I found it:
this sequence in a TU will make the preprocess crash: &#x1E;

**Comment by vince62s** [comment] 2017-01-06 15:58
Another strange thing.
my TMX is 450k seg long.
if I cut it into 2 files it goes fine, as one file it crashes....
But I had used bigger ones in the past.

**Comment by davidecaroselli** [comment] 2017-01-06 19:52
Hi @vince62s 

we made some good improvements in the error logging in the latest commit of MMT, all the details are reported in the log file "traning.log". Unfortunately this was not available in previous versions.

We had some problems with very strange UTF-8 chars (like emoticons) and we found out that it was a JVM bug! So first thing I would suggest to do is update the openjdk:

```
$ sudo apt-get update
$ sudo apt-get --only-upgrade install openjdk-8-jdk
```

Then you could check if everything went well with:

```
$ java -version
java version "1.8.0_111"
...
```
If you have a Java version with suffix "_111" or higher, then you should be ok.

If this doesn't solve the problem, could you create a stub TMX with that single phrase pair that makes MMT crash, and send it to me? I will try to investigate where the problem is.

Thank you!

**Comment by vince62s** [comment] 2017-01-06 20:04
ok I will, should I recompile the last version of MMT too ?
because eventhough I could train my new model, it crashes every time I try to load it ....

**Comment by davidecaroselli** [comment] 2017-01-06 20:17
ok then, if you can create that single-pair TMX and send me also the commands you used to create the engine, I will try to replicate (and solve, of course! :) ) the bug myself.

We haven't heavily tested "nl" tokenizer yet, but we made several bug fixes in the latest master branch, so you could try to compile from source and see if it solves the problem.

**Comment by vince62s** [comment] 2017-01-06 20:21
okay on issue after the other... now I can't recompile.
-- Found the Rocksdb library: /home/moses/ModernMT/build/lib/librocksdb.so /home/moses/ModernMT/build/include
-- Not Found lzma
-- Compiling with OpenMP
CMake Error at /home/moses/ModernMT/src/cmake_modules/FindModernMT.cmake:49 (message):
  Could not find the following ModernMT components: common
Call Stack (most recent call first):
  CMakeLists.txt:92 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by davidecaroselli** [comment] 2017-01-06 21:08
@vince62s just fixed! sorry for that :)

**Comment by vince62s** [comment] 2017-01-06 21:23
okay.
I compiled fine.
But now I realize that you changed some stuff, xconifg related so I need to rebuild my model.
right ?

**Comment by davidecaroselli** [comment] 2017-01-06 21:26
Yes, unfortunately beside the config file, we also made improvements in the models that are no longer backward compatible.

**Comment by vince62s** [comment] 2017-01-06 21:30
ok then will run during the night. thanks.

**Comment by vince62s** [comment] 2017-01-07 11:49
ok only issue remaining is with these sequences
& # x 1E ;
& # x 1F ;
(of course without the spaces)
the rest seems ok.

**Comment by davidecaroselli** [comment] 2017-01-08 17:08
Hi @vince62s 

I've investigated the problem and I checked the XML documentation: those two XML entities are invalid in an XML document as reported here: [W3C XML 1.0 - Charsets](https://www.w3.org/TR/2008/REC-xml-20081126/#charsets).

The question is: who's produced that XML? MMT rewrites all TMX in the first step (cleaning) so please check if the original TMX already contained those invalid sequences: if yes, the TMX are invalid, otherwise it's a MMT problem.

**Comment by vince62s** [comment] 2017-01-08 17:54
it's from Studio 2015, so might be an issue from SDL then.

**Comment by davidecaroselli** [comment] 2017-01-10 12:19
Hi @vince62s 
I've just pushed a fix into branch develop: all invalid XML entities are now replaced with whitespace.
So even if you have an invalid TMX, MMT can now parse it and read it.

Can you confirm that this fix solved your problem?

Davide

**Comment by vince62s** [comment] 2017-01-10 19:34
my NL config is in beta production right now, and on another building new models ....
can't test right now. do you want a small TMX by email ?
would the develop branch be fully running otherwise ?

**Comment by davidecaroselli** [comment] 2017-01-10 19:52
no problem @vince62s , I've already tested the solution on a small TMX containing errors on purpose, and I've also run it on a benchmark of 300M parallel words, so I can say that the fix works as expected!

I'm closing the issue right now but if you find some other issues related to XML Char entities, please reopen it.

Thanks!

**Closed** 2017-01-10 19:51 UTC
Labels: bug

**Comment by vince62s** [comment] 2017-01-17 17:56
I did git pull but I am having an error. Do I need to rerun the setup or is it only in a script ?

**Comment by davidecaroselli** [comment] 2017-01-17 18:14
Yes, I made some changes also in the Java part, so you need to rerun `mvn clean install` from `src/` folder, no need to call `./setup.py` script.
