### ISSUE TITLE
Tag handling issues

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#338] opened 2018-01-23 17:43 UTC
Hello MMT team,

It seems there is an issue with tag handling after processing. 

Here are a couple of examples:

1) Handling of "<" and ">".  
`En: A Compartment with ID &lt;OCID> does not exist. `

`JA: ID が &lt; OCID &gt; のコンパートメントは存在しません。 `

`Expected output: ID<OCID>のコンパートメントは存在しません。
`

> `MMT when processing a string with XML escapes the characters so '<' becomes &lt; apostrophes become &apos; etc. `

2) Another example:
Source string:

`For example, if you want to use the German skin when the user's browser is set to the German locale, and to use the English skin otherwise, use the following <codeph>&lt;skin-family></codeph> entry in the <codeph>trinidad-config.xml</codeph> file:`

Result string:

`Por ejemplo, si desea utilizar la máscara alemana cuando el explorador del usuario se define en la configuración regional alemán y para utilizar la máscara en inglés, utilice la siguiente entrada <codeph>&lt;skin-family&gt;</codeph> en el archivo <codeph>trinidad-config.xml</codeph> :`

> `In this case, MMT has changed the ">" tag of 'skin-family' to an escaped version, but returned the rest correctly. It seems that MMT only has issues when there's single '<' or '>' being escaped.`

One more thing:

Have you noticed any corrupted characters in the output of Japanese or any other Asian language?

Some number strings are corrupted, as question marks:
EN: `-- <completed><month>September</month><year>2017</year></completed>   ` 
JA: `-- <completed><month>???? 年 ? 月</month><year></year></completed>`

I am not sure what is causing this issue.

Thanks in advance for your support. 

Thanks,
Mohamed

**Comment by EtienneAb3d** [comment] 2018-01-24 08:16
In a well-formed XML string, "<" and ">" must be used only for tags delimitations, and all "<" and ">" chars as simple text must be coded "&lt;" and "&gt;". Thus, the problem is not in the MMT output, but rather the fact that your entries are not XML well-formed strings.

**Comment by mzeidhassan** [comment] 2018-01-25 17:39
Thanks @EtienneAb3d for your reply. I appreciate it. I see your point and I have raised the same concern, but I thought that MMT can manage them and display the rendered entity after processing since in real translation scenario, you don't want to have &lt; or &gt; there. Maybe, @davidecaroselli or @AndRossi can clarify this?

I also found another issue with <span> tag. The span tags are omitted in the output for some reason

For example"

`<span sid="1">8</span>Using Groovy Scripts`

is translated as follows:

`8Using Groovy Scripts`

Thanks again!

**Comment by EtienneAb3d** [comment] 2018-01-26 07:44
In real translation scenario you MUST use well-formed XML. Using "<" and ">" chars to code something else than a tag, is forbidden in a well-formed XML. You can't ask MMT to be compliant with your not well-formed XML. It's up to you to provide with well-formed XML, and then to know what to do with it after translation.

If a text is not translated, try to translate without the SPAN tag. Certainly it's an ordinary error of the translator, like they are often doing, and not a problem with the tag itself.

The SPAN tag isn't coding any kind of space. In your example, the SPAN tag is just there to provide with an information on the "8" char. Nothing more. Thus, your rendering example is completely normal.

**Comment by davidecaroselli** [comment] 2018-01-26 10:37
Hi @mzeidhassan 

@EtienneAb3d is right, it's a problem of encoding. You **do** want to have escaped symbols in your queries otherwise is impossible to distinguish XML from text. Let me clarify this point with an example:
```
<b>Do not press</b> the red <button>
```
Is `<button>` an XML tag? No. But it is identical to the bold tag `<b>`. So how can I distinguish the two? `<button>` is in fact text, and I have to escape it:
```
<b>Do not press</b> the red &lt;button&gt;
```
Now MMT can distinguish between actual XML and text that must be translated.
> [...] display the rendered entity after processing since in real translation scenario, you don't want to have &lt;or &gt; there [...]

You don't want the user to see odd **&amp;gt;** or **&amp;lt;** symbols, but this is aUI problem, not at API level. Your client (i.e. a CAT tool) must process the string and highlight the XML tags in some other way, to show the user that those are "separate" elements, for example it can show them in bold:

**&lt;b&gt;** Do not press **&lt;/b&gt;** the red &lt;button&gt;

But when you sent them to the API, in a plain-text format, you **have to** use the XML-entity escaping in order to tell the API what is XML and what isn't.

As a fun fact, try to write a response here on github issue reply with the example I shown and the hit "Preview", you'll see that you canno simply write "&lt;button&gt;", because it's interpreted as HTML, you have to write "&amp;lt;button&amp;gt;"

**Comment by mzeidhassan** [comment] 2018-01-26 16:21
Hi @davidecaroselli ,

Thank you so much for your explanation. I really appreciate taking the time to explain it. 

As for the span tag string:
`<span sid="1">8</span>Using Groovy Scripts`

The issue is not a translator's issue. I tested this string with both EN>JA and EN>ES engines and for some reason, I am getting different results. 

The Spanish output is:
`8Using Groovy Scripts
`
While the Japanese is:

`< span sid =" 1 "> 8 </ span > Groovy スクリプトを使用します
`
Any idea why in Spanish it's not translated and the number is concatenated with the text?

Thanks again for your support and have a good weekend!

Mohamed

**Comment by robertBrnnn** [comment] 2018-01-29 12:04
Hi @davidecaroselli ,

The output @mzeidhassan and I expected from ModernMT for the string
`A Compartment with ID &lt;OCID> does not exist.`

is 

`ID&lt;OCID>のコンパートメントは存在しません。`

We don't expect ModernMT to turn `&lt;` into a <, we expect it to preserve the format of the original string i.e. where there's an `&lt;` in the source we expect `&lt;` in the translation, the same applies to `&gt;`. Instead where ModernMT encounters an escaped tag such as `&lt;OCID>` it escapes the closing brace to `&lt;OCID&gt;`, we expect `&lt;OCID>` in the translation instead.

Also, regarding well formed XML `<b>Do not press</b> the red &lt;button>`, is valid XML, just as our example above is. You don't "have to" escape both the opening and closing braces. Escaping the opening brace alone is enough, and is valid. Escaping the closing brace is optional.


Regarding the second point in @mzeidhassan original post, the string:
`<completed><month>September</month><year>2017</year></completed>`
when sent to ModernMT via the Rest API, we receive the response:
`<completed><month>???? 年 ? 月</month><year></year></completed>`

Have you encountered this?

Thanks,
R.

**Comment by davidecaroselli** [comment] 2018-01-29 17:55
Hi @robertBrnnn !

> We don't expect ModernMT to turn &lt; into a <, we expect it to preserve the format of the original string [...]

Ok, now it makes sense to me. The fact is that the two representations (`&lt;OCID>` and `&lt;OCID&gt;`) are totally equivalent, so there is no effort by MMT to try to keep these conventions because they will produce the same output anyway.

> You don't "have to" escape both the opening and closing braces.

Absolutely right. My point was: you have to do something in order to make it different from `<b>`. IT's perfectly ok to escape it with `&lt;button>` or `&lt;button&gt;`, both are ok and supported by MMT.

> Regarding the second point in @mzeidhassan original post, the string [...]

Unfortunately we encountered those errors too. It is not related to XML, it is a problem with numbers that are not properly ported from source to target. We are currently working on this issue, but we have not final solution yet.

Hope this helps!
Davide

**Comment by robertBrnnn** [comment] 2018-01-30 15:05
Hi @davidecaroselli 

Thanks for your reply.

Yes that's correct, the two representations of the tag are equivalent from the rendered perspective. The requirement for preservation came from others, but we've agreed that it's an excessive request, so you can ignore that issue.

Regarding the other point, that's great to know. Do you have an issue that we can follow, so we know when a possible fix is underway?

Thanks again for your reply, it's greatly appreciated,
R.

**Comment by davidecaroselli** [comment] 2018-01-30 15:38
Hi @robertBrnnn 

I'm going to open the "numbers" issue very soon. Meanwhile I'm closing this issue; as always, feel free to re-open it if you need any further help or you have any questions.

Thank you!
Davide

**Closed by davidecaroselli** 2018-01-30 15:38 UTC
