### ISSUE TITLE
Exception error in thread "main" in step 2 "corpora processing"

### ISSUE THREAD

**Issue by memoday** [ModernMT/MMT#238] opened 2017-03-23 04:52 UTC
Hi David,

I got this error during training. Here it is 

`Exception in thread "main" eu.modernmt.processing.ProcessingException: Unable to find token 'تارىخ' starting from index 0 in sentence "تاریخ مراجعة النص"
	at eu.modernmt.processing.tokenizer.TokenizerOutputTransformer.transform(TokenizerOutputTransformer.java:27)
	at eu.modernmt.processing.tokenizer.TokenizerOutputTransformer.transform(TokenizerOutputTransformer.java:41)
	at eu.modernmt.processing.tokenizer.corenlp.CoreNLPTokenizer.call(CoreNLPTokenizer.java:72)
	at eu.modernmt.processing.tokenizer.corenlp.CoreNLPTokenizer.call(CoreNLPTokenizer.java:26)
	at eu.modernmt.processing.ProcessingPipeline.call(ProcessingPipeline.java:32)
	at eu.modernmt.processing.ProcessingPipeline.call(ProcessingPipeline.java:20)
	at eu.modernmt.training.preprocessing.TrainingPreprocessor$FragmentProcessor.call(TrainingPreprocessor.java:110)
	at eu.modernmt.training.preprocessing.TrainingPreprocessor$FragmentProcessor.call(TrainingPreprocessor.java:85)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-22 21:38:06,216 [INFO] - Training step "Corpora preprocessing" completed in 1m 45s
2017-03-22 21:38:06,216 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/root/ModernMT/cli/engine.py", line 237, in build
    (self._engine.data_path if split_trainingset else None), log=logger.stream)
  File "/root/ModernMT/cli/mt/processing.py", line 148, in process
    shell.execute(command, stdout=log, stderr=log)
  File "/root/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /root/ModernMT/build/mmt-0.14.1.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t ar -v /root/ModernMT/engines/default/models/vocabulary --output /root/ModernMT/runtime/default/tmp/training/preprocessed --input /root/ModernMT/runtime/default/tmp/training/training_corpora --dev /root/ModernMT/engines/default/data/dev --test /root/ModernMT/engines/default/data/test' failed with exit code 1`

I am not sure why it throws this error. 

The training.log shows the following before above error. It might help you triage the issue.

`2017-03-22 21:34:39,277 [INFO] - Training started: engine=default, bilingual=1, monolingual=0, langpair=en-ar
2017-03-22 21:34:39,277 [INFO] - Training step "TMs clean-up" (1/7) started
2017-03-22 21:34:39,278 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.14.1.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /root/ModernMT/runtime/default/tmp/training/clean_tms --input /root/ModernMT/examples/data/train/transnative
2017-03-22 21:34:39,705 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-03-22 21:36:20,783 [INFO] - Training step "TMs clean-up" completed in 1m 41s
2017-03-22 21:36:20,784 [INFO] - Training step "Corpora preprocessing" (2/7) started
2017-03-22 21:36:20,784 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.14.1.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.DomainMapMain --db /root/ModernMT/engines/default/models/db/domains.db -s en -t ar -c /root/ModernMT/runtime/default/tmp/training/clean_tms
2017-03-22 21:36:21,050 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.14.1.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t ar -v /root/ModernMT/engines/default/models/vocabulary --output /root/ModernMT/runtime/default/tmp/training/preprocessed --input /root/ModernMT/runtime/default/tmp/training/training_corpora --dev /root/ModernMT/engines/default/data/dev --test /root/ModernMT/engines/default/data/test
2017-03-22 21:36:21,481 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-03-22 21:36:21,573 INFO  eu.modernmt.vocabulary.rocksdb.RocksDBVocabulary [main] Library rocksvb loaded successfully`

Any idea?

Thanks,
Mohamed

**Comment by AndRossi** [comment] 2017-03-23 12:03
Hi @memoday, 

It seems that there is a bug in the tokenizer we employ for Arabic language.
We are currently trying to fix it, so I'll keep you updated.

Thanks,
Andrea

**Comment by davidecaroselli** [comment] 2017-03-23 15:57
Hi @memoday 

I finally found the problem and I've just pushed the fix in the `develop` branch. I would like to test it before pushing into master so, can you provide me the TMX that was causing the problem?
Otherwise you can test it your self if you prefer: just follow these instructions for [Building MMT from sources](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors), just select the right branch after having cloned MMT:
```
cd ModernMT
git checkout develop
[...]
```

Let me know how do you want to proceed.

Cheers.
Davide

**Comment by memoday** [comment] 2017-03-24 03:52
Thanks David for your prompt reply. The version I have is installed is actually from source. Do I need to install it again from scratch?

I would be grateful if you can direct me to the full command that will take care of the update. I am not so familiar with git. 

Thanks

**Comment by davidecaroselli** [comment] 2017-03-24 09:09
No problem!
I suggest to repeat the procedure from scratch just to be 100% sure you will get the latest code. I arranged the code so that you can simply follow the instruction in [Building MMT from sources](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors) just like you already did.

Let me know if the issue is fixed!

**Comment by memoday** [comment] 2017-03-25 06:49
HI David,

When I use this command, 
`git clone https://github.com/ModernMT/MMT.git ModernMT`

I get this error message

> fatal: unable to access 'https://github.com/ModernMT/MMT.git/': Could not resolve host: github.com

**Comment by memoday** [comment] 2017-03-25 07:00
I think I am having an issue with internet connection. I will check it again and report here. Thanks for your patience!

**Comment by memoday** [comment] 2017-03-25 21:29
OK, I installed the latest version and I get now a different error message:

> ERROR Illegal State: failed to start Cassandra, check log file for more details: /root/ModernMT/runtime/default/logs/embedded-cassandra.log


and here is the output of training.log

`2017-03-25 15:19:37,359 [INFO] - Training started: engine=default, bilingual=1, monolingual=0, langpair=en-ar
2017-03-25 15:19:37,359 [INFO] - Training step "TMs clean-up" (1/7) started
2017-03-25 15:19:37,359 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.15.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /root/ModernMT/runtime/default/tmp/training/clean_tms --input /root/ModernMT/examples/data/train
2017-03-25 15:19:37,793 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-03-25 15:20:10,277 [INFO] - Training step "TMs clean-up" completed in 32s
2017-03-25 15:20:10,278 [INFO] - Training step "Corpora preprocessing" (2/7) started
2017-03-25 15:21:49,395 [INFO] - Training step "Corpora preprocessing" completed in 1m 39s
2017-03-25 15:21:49,396 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/root/ModernMT/cli/engine.py", line 240, in build
    log=logger.stream)
  File "/root/ModernMT/cli/engine.py", line 44, in generate
    cassandra.start()
  File "/root/ModernMT/cli/cluster.py", line 404, in start
    'failed to start Cassandra, check log file for more details: ' + self._log_file)
IllegalStateException
`

**Comment by memoday** [comment] 2017-03-25 21:35
if I type `sudo service cassandra start`, I get the following error:

> Failed to start cassandra.service: Unit cassandra.service not found.

I assume that installing from the source should install cassandra as well. Please let me know.

**Comment by davidecaroselli** [comment] 2017-03-26 11:31
Hi @memoday sorry for that problem. It seems there is a problem with the new component in v0.15.

So, in order to debug it, can you please also attach the file `/root/ModernMT/runtime/default/logs/embedded-cassandra.log`? 

Furthermore:
* Have you successfully run the command `./setup.py`, right?
* This problem arises during `./mmt create` right? Can you please report the whole command you used? (i.e. `./mmt create en it examples/data/train`).

The command `sudo service cassandra start` won't work because MMT uses a local installation of Cassandra (it's inside the `vendor` folder!) so it's not visible by the ubuntu system.

Thanks for your patience!
Davide

**Comment by memoday** [comment] 2017-03-27 00:07
Hi David,

It's almost empty. It has only these 2 lines

`Running Cassandra as root user or group is not recommended - please start Cassa$
If you really want to force running Cassandra as root, use -R command line opti$`

**Comment by memoday** [comment] 2017-03-27 05:40
Hi David,

So, I deleted the whole ModernMT directory and installed it again from source. I see that cassandra was installed successfully. Here is what I see in terminal:

`[INFO] Reactor Summary:
[INFO]
[INFO] MMT Root Module .................................... SUCCESS [  0.567 s]
[INFO] Common components and interfaces for ModernMT ...... SUCCESS [  4.339 s]
[INFO] Text Processing Module ............................. SUCCESS [ 31.969 s]
[INFO] FastAlign-based aligner implementation ............. SUCCESS [  9.488 s]
[INFO] Lucene-based Context Analyzer ...................... SUCCESS [  1.208 s]
[INFO] Phrase-based decoder implementation ................ SUCCESS [04:07 min]
[INFO] RocksDB-based Vocabulary ........................... SUCCESS [  5.782 s]
[INFO] Cassandra persistence implementation ............... SUCCESS [  0.678 s]
[INFO] MMT Core ........................................... SUCCESS [  2.532 s]
[INFO] Jetty-based REST API ............................... SUCCESS [  1.443 s]
[INFO] Command-line interface ............................. SUCCESS [ 20.812 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:26 min
[INFO] Finished at: 2017-03-26T23:25:35-06:00
[INFO] Final Memory: 163M/1538M
[INFO] ------------------------------------------------------------------------
root@ubuntu:~/ModernMT/src# cd ..
root@ubuntu:~/ModernMT# ./setup.py
Installing cassandra-3.10... DONE
Installing kafka-0.10.0.1... DONE
` 


I got the same error though after step 2. Here is it from the terminal:

`=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ar

INFO: (1 of 7) TMs clean-up...                                         DONE (in 31s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 1m 39s)
ERROR Illegal State: failed to start Cassandra, check log file for more details: /root/ModernMT/runtime/default/logs/embedded-cassandra.log
`
I also opened again 'embedded-cassandra.log', but the same 2 lines above. 

I hope this helps.

thanks,
Mohamed Zeid

**Comment by davidecaroselli** [comment] 2017-03-27 09:09
Hi @memoday ,

we have just pushed the fix on the `master` branch. In order to receive it, cd into the ModernMT folder and execute:
```
git pull origin master
```
You should see an output like the following:
```
[...]
Fast-forward
 cli/cluster.py                                                                                  |  2 +-
[...]
```
Now you can run again the training: no need to recompile anything!

About the problem: you're running MMT from root user. While this is usually not a best practice, it is absolutely legitimate. The new fix allows Cassandra to be run by root user.

Let me know if this solved your issue!

**Comment by memoday** [comment] 2017-03-28 02:15
Perfect, Davide! It works perfectly now. Thanks a million for the amazing support and follow-up. I am grateful.

**Comment by davidecaroselli** [comment] 2017-03-28 08:36
Great! @memoday it's always a pleasure to collaborate with you!
Cheers.

**Closed by davidecaroselli** 2017-03-28 08:36 UTC
Labels: bug
