### ISSUE TITLE
InterpolatedLM RocksDB fails with a single large training file ("File is too large for PlainTableReader!")

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#195] opened 2016-11-15 17:47 UTC
With a single large training file (containing > 28M words) the creation of the db with "create_alm" appears ok, but trying to read it (e.g. starting the engine or doing a simple query with "query") the java/query programs take a long time and then fail with this error

```
terminate called after throwing an instance of 'rockslm::db::storage_exception'
  what():  Not implemented: File is too large for PlainTableReader!

```
Looking into the rocksDB code, the problem is in the method PlainTableReader::Open() in file
`$MMT_HOME/vendor/rocksdb/table/plain_table_reader.cc`
whose piece of code is:
```
PlainTableReader::Open(...) {
  if (file_size > PlainTableIndex::kMaxFileSize) {
    return Status::NotSupported("File is too large for PlainTableReader!");
  }
```

This problem, spotted in v0.13 is still present in v0.14-alpha.

**Comment by nicolabertoldi** [comment] 2016-11-16 07:41
discussing time ago with Davide, we suggested to change the "format" of the key in the DB.
It sould solve the problem of the file size, but (maybe) it will increase query time; we should pay attention and measure this consequence.

Now the key is "domain ngram", the proposal is to changed as "ngram key",
so that the priority access is through the first word of the ngram, and not through the domain

To do this the following function of "NgramStorage.cpp" should be changed accordingly
static inline string SerializeKey(domain_t domain, dbkey_t key)
Is it enough?

NgramStorage is built as follows
options.prefix_extractor.reset(NewNoopTransform());
options.table_factory.reset(NewPlainTableFactory(plainTableOptions));
options.memtable_prefix_bloom_bits = 1024 * 1024 * 8;

Does this mean that "prefix" is set to 23 bits; as both words and domain are used, no change is actually needed here. Right?

Moreover, no change is required in the object which performs the update, right?


Nicola

**Comment by cattoni** [comment] 2016-11-16 08:03
I provide more precise details on this issue.

The reported logs were generated by the old version v0.13 in beginning of October.

With the  current version v0.14-alpha the failure happens during "mmt create", namely during the step 
"(6 of 7) Language Model training", with the following log:
```
19:41:07,951 [DEBUG] - Shell exec: /home/ubuntu/ModernMT/build/bin/create_slm --discount_fallback -o 5 --model /home/ubuntu/ModernMT/engines/demo.en-de/models/lm/background.slm -S 78% -T /home/ubuntu/ModernMT/runtime/demo.en-de/tmp/training/lm/slm.temp --prune 0 0 1
2016-11-14 19:45:37,511 [DEBUG] - Shell exec: /home/ubuntu/ModernMT/build/bin/create_alm -m /home/ubuntu/ModernMT/engines/demo.en-de/models/lm/foreground.alm -i /home/ubuntu/ModernMT/runtime/demo.en-de/tmp/training/lm/alm_train -b 100000000
 DONE (in 2023s)
ERROR Unexpected exception:
        Command '/home/ubuntu/ModernMT/build/bin/create_alm -m /home/ubuntu/ModernMT/engines/demo.en-de/models/lm/foreground.alm -i /home/ubuntu/ModernMT/runtime/demo.en-de/tmp/training/lm/alm_train -b 100000000' failed with exit code -6
```

To overcome the problem, I had to split the largest files into small files (each with max 1M lines and 25M words): with this solution models are created, loaded and used successfully. The drawback is that the domains changes.

**Comment by nicolabertoldi** [comment] 2016-11-17 17:30
The failure is not related to the key.

Instead, the failure is related to the buffer size used in create_alm.

Not clear why but having a too large value (10e^8) causes the error with any training data.
My suspect is that the batch used as buffer before actual writing into the persistent DB
uses a temporary file (or a pseudo-file) which becomes too big with respect to maximum allowed size (2Gb)
[see https://github.com/facebook/rocksdb/issues/927]

In my investigation also noticed that using a smaller value for the buffer size increases speed,
as you can see from these figures

Creation of the adaptive LM on the following 7 domains.
     lines	words
    194,602    3,679,184 _TMP_lm_data_/1.de
   2,330,617   47,666,386 _TMP_lm_data_/2.de
    240,314    6,150,791 _TMP_lm_data_/3.de
   9,782,544   88,089,686 _TMP_lm_data_/4.de
    117,530    4,521,513 _TMP_lm_data_/5.de
   1,860,118   50,081,924 _TMP_lm_data_/6.de
   2,339,917   53,131,363 _TMP_lm_data_/7.de

Time to complete the training of the adaptive LM with various buffer sizes
buffer_size   speed (real_time)
   1.0e^4	2m30.698s
   5.0e^4	2m32.810s
   1.0e^5	2m28.435s
   5.0e^5	2m42.035s
   1.0e^6	2m45.617s
   5.0e^6	4m42.120s
   1.0e^7	9m10.923s
   1.0e^8	failure

Moreover, although I did not measure the RAM consumption carefully,
I noticed that the RAM consumption is smaller with smaller buffer values.

Hence, according to this analysis, I changed the value used in MMT.
I set the value to  1.0e^5

**Comment by davidecaroselli** [comment] 2016-11-17 17:32
Thanks @nicolabertoldi 
amazing job!

**Comment by davidecaroselli** [comment] 2016-12-06 17:47
Re-opening because the bug is still there and it's not solved

**Comment by davidecaroselli** [comment] 2016-12-13 15:20
I've just asked @cidermole to contribute in solving this bug, he will write any news asap.
Thanks!

**Comment by cidermole** [comment] 2016-12-13 19:44
Couldn't reproduce using 42 M source words with `features/moses2` which has the most recent models merged from `develop`.

```
$ wc /home/ubuntu/data/benchmark-1.1/data/train-concat-50m/*
  3375246  42082679 270271296 /home/ubuntu/data/benchmark-1.1/data/train-concat-50m/h50m.en
  3375246  45571263 316023845 /home/ubuntu/data/benchmark-1.1/data/train-concat-50m/h50m.it
  6750492  87653942 586295141 total
```

ran commands:

```
./mmt create -e b11-50m en it /home/ubuntu/data/benchmark-1.1/data/train-concat-50m
./mmt start -e b11-50m
curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tool
```

I assume it should crash in `mmt start`?

**Comment by cattoni** [comment] 2016-12-13 20:57
Hi @cidermole 

With the past versions "mmt create" did not report any problem, but:

1) the size of the DB dir 
`$MMT_HOME/engines/$ENGINE/models/lm/foreground.alm/_data/`
was extremely small wrt the expected size (typically it contained only one small ".sst" file, instead of several very large ".sst" files)

2) "mmt start" crashed (was unable to load such DB).

**Comment by davidecaroselli** [comment] 2016-12-14 08:27
@cattoni can you please send the data you used to reproduce the bug to @cidermole?

Thanks!

**Comment by cattoni** [comment] 2016-12-14 08:45
Sure.

**Comment by davidecaroselli** [comment] 2017-01-20 14:34
After a period of debugging and testing, we haven't experienced this issue anymore. Unfortunately we could not identify exactly the cause of the problems, but seems that this issue is no more present on newer version of RocksDB and MMT.
We tested many huge training set, even the exact same data that lead to this problem at the beginning, but it now works as expected.

For this reason we can consider closed this issue. If someone can still reproduce this bug with new MMT versions, please re-open this issue.

Thanks to all!

**Closed by davidecaroselli** 2017-01-20 14:34 UTC
Labels: bug, high-priority
