### ISSUE TITLE
TMX with utf-16le encoding considered invalid

### ISSUE THREAD

**Issue by gdaine** [ModernMT/MMT#293] opened 2017-10-30 20:24 UTC
Hi,
I have never been able to use tmx files for creating engines or importing new data. After a lot of trial and error, today I managed to import data after converting the TMX file to utf-8. 
These were standard tmx exports from memoQ, encoded in utf-16LE (which is legal according to the TMX specs, AFAIK).
The error message in node.log gave me a clue on where to look (copied below).

Is this by design, or is there some other issue which may also be causing it? 

Perhaps a note in the relevant part of the wiki would be useful, if this is indeed the case.

Gary

Error message (from node.log):

Invalid TMX ES.tmx
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:56)
	at eu.modernmt.cluster.kafka.KafkaDataManager.upload(KafkaDataManager.java:203)
	... 28 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,2]
Message: The markup in the document preceding the root element must be well-formed.

**Comment by EtienneAb3d** [comment] 2017-10-31 07:36
Just an idea : it sounds like a problem while reading the BOM bytes.

**Comment by AndRossi** [comment] 2017-10-31 12:20
Hello @gdaine, 

Thank you for trying ModernMT :)
As you pointed out, by design ModernMT requires data to be UTF-8 encoded.

I'm sorry this information was not included in the documentation.
I have promptly added it in the [engine creation page](https://github.com/ModernMT/MMT/wiki/Create-an-engine-from-scratch) and I have also added a new related question in the [FAQ page](https://github.com/ModernMT/MMT/wiki/FAQs).

Thank you for your support!

Best,

Andrea

**Comment by gdaine** [comment] 2017-10-31 16:39
Thanks for the clarification (and the documentation update). 
And congratulations on an amazing program!
Gary

**Comment by AndRossi** [comment] 2017-10-31 17:34
You're welcome!
I'm glad you appreciate MMT :) 

Since this issue was cleared I'm going to close it now.
For any problem or further doubt, however, don't hesitate to reopen it.

Have a nice day!

Andrea

**Closed by AndRossi** 2017-10-31 17:34 UTC
