### ISSUE TITLE
Add to local ModernMT works, but update does not

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#388] opened 2018-08-06 21:11 UTC
All translations are added to memory id 1.

`    public function addToMemoryContent($source, $target, $sentence, $translation) {
        return $this->send('POST', "$this->baseUrl/memories/1/corpus", [
                'source' => $source, 'target' => $target, 'sentence' => $sentence, 'translation' => $translation
            ]);
    }`

Works. I can attest the data is actually added to the memory, as I see the network has learnt from the suggestions in later sentences.

However

`    public function updateMemoryContent($source, $target, $sentence, $translation, $oldSentence, $oldTranslation) {
        return $this->send('PUT', "$this->baseUrl/memories/1/content", [
                'source' => $source, 'target' => $target, 'sentence' => $sentence, 'translation' => $translation,
                'old_sentence' => $oldSentence, 'old_translation' => $oldTranslation
            ]);
            // }
        }`

...gives Invalid API endpoint.

Now if I go manually to $this->baseUrl/memories/1, I get a neat response. If I go to $this->baseUrl/memories/1/corpus, I get invalid API endpoint (even though addToMemoryContent seems to have no issues with this). If I go to $this->baseUrl/memories/1/content, I once again get invalid API endpoint, but that was to be expected considering the results above.

What's going on here? Does Update not work on local networks?

**Comment by davidecaroselli** [comment] 2018-08-20 12:40
Hi @LoekvanKooten 

I've just made the v3.0 release. We have run several tests and I confirm that both update and import seems to work correctly now. Can you please double check?

**Comment by LoekvanKooten** [comment] 2018-08-21 06:44
@davidecaroselli No, this is still not working.

```
        file_put_contents('G:\Temp\MMT Update1.txt', print_r($result, true) . PHP_EOL . $source . PHP_EOL . $target . PHP_EOL . $row['source'] . PHP_EOL . $row['target']);
        $result = $mmt->updateMemoryContent($source, $target, $sourcemmt, $targetmmt, $oldsentencemmt, $oldtranslationmmt);
        file_put_contents('G:\Temp\MMT Update2.txt', print_r($result, true) . PHP_EOL . $sourcemmt . PHP_EOL . $targetmmt);
```

...gives no result or whatsoever. Add works, using exactly the same variables.

MMT Update 1.txt is neatly written:

```
mysqli_result Object
(
    [current_field] => 0
    [field_count] => 3
    [lengths] => Array
        (
            [0] => 217
            [1] => 249
            [2] => 36
        )

    [num_rows] => 1
    [type] => 0
)

*REQUIRES BATTLEFIELD V ON XBOX ONE (SOLD SEPARATELY), ALL GAME UPDATES, INTERNET CONNECTION AND AN EA ACCOUNT.  NO WEAPON, VEHICLE OR GEAR MANUFACTURER IS AFFILIATED WITH OR HAS SPONSORED OR ENDORSED THIS GAME.
*VEREIST BATTLEFIELD V OP XBOX ONE (APART VERKRIJGBAAR), ALLE GAME UPDATES, INTERNETVERBINDING EN EEN EA-ACCOUNT.  DIT SPEL IS NIET GELIEERD AAN EN WORDT NIET GESPONSORD OF ONDERSCHREVEN DOOR FABRIKANTEN VAN WAPENS, VOERTUIGEN OF UITRUSTINGEN.
*REQUIRES BATTLEFIELD V ON XBOX ONE (SOLD SEPARATELY), ALL GAME UPDATES, INTERNET CONNECTION AND AN EA ACCOUNT.  NO WEAPON, VEHICLE OR GEAR MANUFACTURER IS AFFILIATED WITH OR HAS SPONSORED OR ENDORSED THIS GAME.
*VEREIST BATTLEFIELD V OP XBOX ONE (APART VERKRIJGBAAR), ALLE GAME UPDATES, INTERNETVERBINDING EN EEN EA-ACCOUNT.  DIT SPEL IS NIET GELIEERD AAN EN WORDT NIET GESPONSORD OF ONDERSCHREVEN DOOR FABRIKANTEN VAN WAPENS, VOERTUIGEN OF UITRUSTINGEN.
```

MMT Update 2.txt is never written.

**Comment by davidecaroselli** [comment] 2018-08-22 11:14
Hi @LoekvanKooten 

I suspect there should be an error on your PHP code. One thing I can notice right away is the fact that, in order to update a memory content, you need to specify the id of the memory, that is missing from your method call. 

If that is the file I gave to you some time ago, then the method signature is:
```php
public function updateMemoryContent($id, $source, $target, $sentence, $translation, $oldSentence, $oldTranslation);
```

So the problem is that you're not passing the ```$id``` parameter.

**Comment by LoekvanKooten** [comment] 2018-08-22 16:34
@davidecaroselli I had rewritten en simplified said routine as it was for local use only, but:

$result = $mmt->updateMemoryContent(1, $source, $target, $sourcemmt, $targetmmt, $oldsentencemmt, $oldtranslationmmt);

...gives exactly the same result (the memory id is 1, without doubt).

**Comment by davidecaroselli** [comment] 2018-08-22 16:41
Can you please add here the `runtime/default/log/node.log` file right after this call please? Let's see if the ModernMT engine is receiving the request.

**Comment by LoekvanKooten** [comment] 2018-08-22 16:46
I'm afraid the log is empty and that ModernMT is receiving absolutely nothing.

**Comment by davidecaroselli** [comment] 2018-08-22 17:04
well... that's definitely the problem. Something on the PHP side is misconfigured and it is pointing to an invalid host, I think.

You have the debug the PHP part and double-check the steps from the API call to its actual execution.

**Comment by LoekvanKooten** [comment] 2018-08-22 17:08
It seems the problem is in MMT's code. I added the following line directly in ModernMT's PHP class:

```
public function updateMemoryContent($id, $source, $target, $sentence, $translation, $oldSentence, $oldTranslation) {
        file_put_contents('G:\Temp\updateMemoryContent.txt', $id . PHP_EOL . $source . PHP_EOL . $target . PHP_EOL .  $sentence . PHP_EOL . $translation . PHP_EOL . $oldSentence . PHP_EOL . $oldTranslation);
        if (is_array($id)) {
...
```

The contents of updateMemoryContent.txt are as follows:

```
1
＜0＞{}＜1＞＜2＞≪0≫＜3＞INSTALLATION,＜4＞≪1≫＜5＞＜6＞≪2≫＜7＞ OPERATION AND＜8＞{}＜9＞＜10＞≪3≫＜11＞
＜0＞{}＜1＞＜2＞≪0≫＜3＞INSTALLATIE-,＜4＞≪1≫＜5＞＜6＞≪2≫＜7＞ BEDIENINGS- EN＜8＞{}＜9＞＜10＞≪3≫＜11＞
<0>{}<1><2><0><3>INSTALLATION,<4><1><5><6><2><7> OPERATION AND<8>{}<9><10><3><11>
<0>{}<1><2><0><3>INSTALLATIE-,<4><1><5><6><2><7> BEDIENINGS- EN<8>{}<9><10><3><11>
<0>{}<1><2><0><3>INSTALLATION,<4><1><5><6><2><7> OPERATION AND<8>{}<9><10><3><11>
<0>{}<1><2><0><3>INSTALLATIE-,<4><1><5><6><2><7> BEDIENINGS- EN<8>{}<9><10><3><11>
```

Still, ModernMT gets nothing. The funny thing is that addToMemoryContent in exactly the same class gives no problems or whatsoever.

**Comment by davidecaroselli** [comment] 2018-08-22 17:12
Just realized: your `source` and `target` are arbitrary texts, they should be the source and target languages.

**Comment by davidecaroselli** [comment] 2018-08-22 17:17
BTW, you should be able to see the error in the `node.log`, and if you say that the addToMemory works as expected, you should see the API call in `node.log`; but you said:

> I'm afraid the log is empty and that ModernMT is receiving absolutely nothing.

How ModernMT is able to return a valid result for AddToMemory if it is not receiving nothing at all?

**Comment by LoekvanKooten** [comment] 2018-08-22 17:30
Apache gives:

`[Wed Aug 22 19:29:29.450327 2018] [php7:error] [pid 15304:tid 1960] [client ::1:50920] PHP Fatal error:  Uncaught MMT\\MMTServiceApiException: Invalid API endpoint in G:\\Xampp\\htdocs\\ModernMT\\MMTServiceApiException.php:18\nStack trace:\n#0 G:\\Xampp\\htdocs\\ModernMT\\MMTServiceApi.php(395): MMT\\MMTServiceApiException::fromJSONResponse(Array)\n#1 G:\\Xampp\\htdocs\\ModernMT\\MMTServiceApi.php(377): MMT\\MMTServiceApi->parse('{"status":404,"...')\n#2 G:\\Xampp\\htdocs\\ModernMT\\MMTServiceApi.php(188): MMT\\MMTServiceApi->send('PUT', 'http://192.168....', 'source=en&targe...')\n#3 G:\\Xampp\\htdocs\\ModernMT\\functions.php(105): MMT\\MMTServiceApi->updateMemoryContent(1, 'en', 'nl', '<0>{}<1><2><0><...', '<0>{}<1><2><0><...', '<0>{}<1><2><0><...', '<0>{}<1><2><0><...')\n#4 G:\\Xampp\\htdocs\\ModernMT\\ajaxUpdateTrans.php(226): insertSentence('\\xEF\\xBC\\x9C0\\xEF\\xBC\\x9E{}\\xEF\\xBC\\x9C1\\xEF\\xBC...', '\\xEF\\xBC\\x9C0\\xEF\\xBC\\x9E{}\\xEF\\xBC\\x9C1\\xEF\\xBC...', 'Univox Group', 'G:\\\\\\\\PROJECTS\\\\\\\\U...', '0')\n#5 {main}\n  thrown in G:\\Xampp\\htdocs\\ModernMT\\MMTServiceApiException.php on line 18, referer: http://localhost/ModernMT/translateb.php?folder=G%3A%5CPROJECTS%5CUnivox+Group%5C180815b`

**Comment by davidecaroselli** [comment] 2018-08-23 11:16
Hi @LoekvanKooten 

that is starting to be helpful :). In general: when invoking ModernMT you should `try/catch` any `MMT\MMTServiceApiException` an gracefully handle and print the error.

From that log I see only a bit of the ModernMT result: `{"status":404,"...`
I think that the problem is that the memory with id `1` does not exist. Can you please check that?

**Comment by LoekvanKooten** [comment] 2018-08-23 11:33
@davidecaroselli Thank you for your help! Yes, the end point is missing it says. However, memory 1 exists. When I use Get Memories, I neatly get an overview presenting me one memory with number 1.

**Comment by LoekvanKooten** [comment] 2018-08-23 11:33
`Getting memories...
Status:
Querying http://192.168.178.30:8045/memories

result:
HTTP/1.1 200 OK Date: Thu, 23 Aug 2018 11:33:29 GMT Content-Type: application/json; charset=utf-8 Content-Length: 49 Server: Jetty(9.3.z-SNAPSHOT) {"status":200,"data":[{"id":1,"name":"engdut"}]}

preg_match:
{"status":200,"data":[{"id":1,"name":"engdut"}]}

array(2) { ["status"]=> int(200) ["data"]=> array(1) { [0]=> array(2) { ["id"]=> int(1) ["name"]=> string(6) "engdut" } } }

id: 1
name: engdut

status: 200`

**Comment by davidecaroselli** [comment] 2018-08-29 16:56
Ok, can you please create a super simple and self-contained example of this problem, and send it to me?

I am unable to replicate that unfortunately.

**Comment by LoekvanKooten** [comment] 2018-08-30 07:34
@davidecaroselli What exactly do you need? Just the PHP code?

**Comment by LoekvanKooten** [comment] 2018-08-30 07:35
Is there any way we can test said end point on Ubuntu itself?

**Comment by davidecaroselli** [comment] 2018-08-30 08:37
> Is there any way we can test said end point on Ubuntu itself?

Sure, just run:
```bash
curl -X PUT http://localhost:8045/memories/1/corpus \
     -d "source=en" \
     -d "target=nl" \
     -d "sentence=Hello world" \
     -d "translation=Hallo Wereld" \
     -d "old_sentence=Hello world" \
     -d "old_translation=Hllo Wereld" \
     | python -mjson.tool
```

**Comment by LoekvanKooten** [comment] 2018-08-30 08:45
Solved!

MMTServiceAPI said:
return $this->send('PUT', "$this->baseUrl/memories/content"

Which should read:
return $this->send('PUT', "$this->baseUrl/memories/corpus"

**Comment by davidecaroselli** [comment] 2018-08-30 08:53
Great! Sorry for not having suggested to run the cURL directly before  :)
I'm closing this issue, if there are any other problems, please feel free to re-open it!

**Closed by davidecaroselli** 2018-08-30 08:53 UTC
Labels: invalid
