### ISSUE TITLE
0.13 dev vs 0.12 - Lower BLEU

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#140] opened 2016-05-27 06:17 UTC
Using the a 0.13 Develop build provided by Davide yesterday.

I had this results on the WMT15 Task Data + OPUS

0.12 Stable, no tuning -> 17.44
0.13 Dev, no tuning -> 14.13

0.12 Stable, WMT tuning -> 19.24
0.13 Dev, WMT tuning -> 18.21

**Comment by davidecaroselli** [comment] 2016-05-27 08:42
I'm running right now a test on benchmark 1.1 to see if there is the same BLEU drop. I'll post the result asap.

**Comment by davidecaroselli** [comment] 2016-05-27 12:37
@marcotrombetti I just finished the tests on benchmark 1.1. On that data 0.13 is performing better than 0.12:

0.12-stable -> 57.48 
0.13-dev -> 59.10

but I found some inconsistencies with internal "in-0.13" results. I'll try to investigate more.

**Comment by marcotrombetti** [comment] 2016-05-27 13:15
@davidecaroselli are you testing the same build you gave me?

**Comment by davidecaroselli** [comment] 2016-05-27 13:16
yes, the exact same build (the one I gave you yesterday)

**Comment by davidecaroselli** [comment] 2016-05-27 13:57
> but I found some inconsistencies with internal "in-0.13" results. I'll try to investigate more.

After a call with @cidermole I realized that it's everything ok with the test results so, no issues.
My best guess is that we have customized the technology to work very well in a particular business case, and it is performing not so well in a totally different case (WMT).

We **need** to provide some sort of "backoff" behavior.

**Comment by davidecaroselli** [comment] 2016-05-27 23:06
@marcotrombetti @luca-mastrostefano @mfederico @cidermole I've got it!

I understood why we lost 1 BLEU point with MMT 0.13, and the good news is: it's not even a bug!
The cause is: **rare-chars normalization**.

The old version of MMT, 0.12, made a normalization of both reference and translation in order to normalize "rare" characters, for example:
- **reference**: « Ciao » (notice the guillemets)
- **MMT 0.12**: " Ciao " (notice regular double quotes)

it was normalized like this:

- **reference**: « Ciao » -> " Ciao "
- **MMT 0.12**: " Ciao " -> " Ciao "

so, as a result, the score on that translation was 100% match: **the normalization hid the error**.
In the new MMT 0.13, we removed this normalization to make a more **fair test**, so the rare-chars normalization was totally removed. In the new MMT the example shown is not going to be normalized:

- **reference**: « Ciao »
- **MMT 0.13**: " Ciao "

so the example translation is correct only for 1 token out of 3 (33%)
So question is: **is MMT 0.13 better than 0.12?**
And the answer is very simple: **Yes**

because, in internal test we made, if we evaluate MMT 0.12 output with 0.13 evaluation tool, we measure a loss of more than 1 BLEU point.

Starting from MMT 0.13 we need to solve issues https://github.com/ModernMT/MMT/issues/130 and https://github.com/ModernMT/MMT/issues/129 to gain more than 1 BLEU point.

*Note: I close this issue right now because it has been proved not to be an actual bug, but the result of a different way of testing. If you think this issue is still pending for some reason, please reopen it.*

**Closed by davidecaroselli** 2016-05-27 23:06 UTC
Labels: bug, high-priority
