### ISSUE TITLE
missing $MMT_HOME/build/bin/extractor

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#206] opened 2016-12-02 08:44 UTC
with branch features/moses2, "mmt tune" fails.
The reason appears to be the missing executable
$MMT_HOME/build/bin/extractor

Actually with features/moses2 the $MMT_HOME/build/bin directory contains 8 executables, while the previous version (branch develop) there were 25

**Comment by davidecaroselli** [comment] 2016-12-02 09:11
@cidermole could you please re-integrate the missing binaries? Without them we could not consider completed the migration to the new decoder

@cattoni as a temporary solution, link back the missing files. You can find them in the binary release of 0.14 for example. Could you also please list all the missing files that we need in order to run tuning?

Thanks!

**Comment by cattoni** [comment] 2016-12-02 11:41
After copying from a previous version the following 5 binaries:

`extractor evaluator kbmira mert pro`

mmt tune starts correctly and executes til step (3 o 4) where it fails with error:

`File not found: /tmp/tmp02ju54 (interpreted as /tmp/tmp02ju54). at /home/ubuntu/ModernMT/cli/opt/mert-moses.perl line 494.
`
The error persists even after adding (with symbolic link) all the remaining binaries.

**Comment by davidecaroselli** [comment] 2016-12-13 15:23
Hi @cattoni ,
@cidermole has solved this issue and pushed into branch features/moses2 that he's tested.

I close this issue for the moment, if you experience some problems, please report them here and re-open the issue. Thank you!

**Comment by cattoni** [comment] 2016-12-13 18:18
With the new system,  "mmt tune" still fails with this error:

```
INFO: (3 of 4) Tuning...                                               DONE (in 32s)
ERROR Unexpected exception:
	Command '/home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.en /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.it /home/ubuntu/NEW_ModernMT/cli/opt/mertinterface.py /tmp/tmpxvdDF0 --threads 16 --mertdir /home/ubuntu/NEW_ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --predictable-seeds --maximum-iterations=25' failed with exit code 2
Traceback (most recent call last):
  File "./mmt", line 589, in <module>
    main()
  File "./mmt", line 567, in main
    actions[command](args)
  File "./mmt", line 115, in main_tune
    random_seeds=args.random_seeds, max_iterations=args.max_iterations)
  File "/home/ubuntu/NEW_ModernMT/cli/cluster.py", line 549, in tune
    shell.execute(' '.join(command), stdout=log, stderr=log)
  File "/home/ubuntu/NEW_ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.en /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/corpus.it /home/ubuntu/NEW_ModernMT/cli/opt/mertinterface.py /tmp/tmpxvdDF0 --threads 16 --mertdir /home/ubuntu/NEW_ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /home/ubuntu/NEW_ModernMT/runtime/ex1/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --predictable-seeds --maximum-iterations=25' failed with exit code 2
```

The execution of the above shell command on the command line reports:

```
Using SCRIPTS_ROOTDIR: /home/ubuntu/NEW_ModernMT/cli/opt
File not found: /tmp/tmpxvdDF0 (interpreted as /tmp/tmpxvdDF0). at /home/ubuntu/NEW_ModernMT/cli/opt/mert-moses.perl line 494.
```

The directory runtime/$ENGINE/tmp/tuning/mert/ contains few files:

```
rw-rw-r-- 1 ubuntu ubuntu    167 Dec 13 18:08 features.list
-rw-rw-r-- 1 ubuntu ubuntu 205274 Dec 13 18:08 run1.best100.out
-rw-rw-r-- 1 ubuntu ubuntu    189 Dec 13 18:08 run1.dense
-rw-rw-r-- 1 ubuntu ubuntu    419 Dec 13 18:08 run1.moses.ini
-rw-rw-r-- 1 ubuntu ubuntu   1571 Dec 13 18:08 run1.out
```

It appears that only 2 of the 29 input sentences have been translates (run1.out  contains 2 lines, run1.best100.out 200 lines).


The new system info: 
branch features/moses2
commit 80e8938dc527a0980d652ab7b0c9409d0109c85d
Author: David Madl <git@abanbytes.eu>
Date:   Fri Dec 9 14:26:38 2016 +0100

**Comment by davidecaroselli** [comment] 2016-12-14 08:23
@cattoni the error about the missing file is not the actual error: a temp file is created by the python script and it's automatically removed when the script ends. You can prevent it just by *touch* it and rerun the command.

In order to reproduce the bug, which data have you used?

@cidermole could you please investigate this issue?

**Comment by cattoni** [comment] 2016-12-14 08:43
Ok about the temp file.

The data used were those in $MMT_HOME/example.
Basically I've run the default example in README.md.
 
The exact sequence was:

```
cd $MMT_HOME
mmt create en it examples/data/train -e ex1
mmt start -e ex1
mmt tune -e ex1 -d
```

I've just given a different name to the default engine.

**Comment by cidermole** [comment] 2016-12-20 16:49
I made #209 because this is now a separate issue.

**Closed by cidermole** 2016-12-20 16:49 UTC
Labels: bug, high-priority
