### ISSUE TITLE
Training the machine to handle non-breaking spaces/whitespace

### ISSUE THREAD

**Issue by martinbrain** [ModernMT/MMT#294] opened 2017-10-31 09:40 UTC
We have trained machines for en fr and en de that often encounter places where, acccording to grammar rules, non-breaking spaces are required.   For example "hello!" in en should become "salut !" in fr (with the nbsp).  Or within phrases things like "100% cotton" - which should become "100 % coton" (again, with the nbsp between 100 and %).

We trained with 150mb of data, around 1.2m segments that have these forms relatively regularly, but the machine does not pick up the change.  We have also tried adding examples to see if the on-the-fly adaptation handles it, but still not giving the right result.

Should we build a post-process?

Thanks

**Comment by AndRossi** [comment] 2017-10-31 11:52
Hello @martinbrain,
We're glad you are trying ModernMT.

The problem you are experiencing is related to the way ModenMT performs tokenization.
By design, in MMT non breakable spaces are transformed into whitespaces during preprocessing phases, and then the tokenized sentences are used to train the models.
This explains why regardless of the amount of data you imported in your engine, it did not "learn" to handle nbsp :) 

The good news is that you don't have to feed your models with more data to make them "learn" this rule: as you expected it's something that a post-processor can handle.

Is it possible for you to draft a complete rule of the cases in which nbsp is required?
If so, it should not be hard for us to implement a custom post-processor to suit your needs.

Thanks for your support.

Have a nice day!

Andrea

**Comment by martinbrain** [comment] 2017-10-31 11:57
Thanks Andrea!   

Rather than ask for your support in setting up the post-process we would benefit from having the ability to run such a process ourselves, since we are likely to find other such rules on this and other content.

We have some ideas on how to implement that, but I wondered what your advice might be, since this is new for us?  Is the post-processor you propose something that we could control within the MMT tool?

**Comment by AndRossi** [comment] 2017-10-31 15:33
Hi @martinbrain, 

Of course you can create the post-processor by yourselves :) 

The post-processor needs to be a Java class implementing the abstract class `TextProcessor<Translation, Translation>`.
You can find the TextProcessor.java file in path `ModernMT/src/textprocessing/src/main/java/eu/modernmt/processing/TextProcessor.java`.

Your post-processor class must thus provide an implementation to the abstract `call` method.
It should something like this:

```java
    
public Translation call(Translation translation, Map<String, Object> metadata) throws ProcessingException {
...
}
```

To integrate your processor in the ModernMT pipeline, so that your post-processor `call` method is executed during the post-processing, all you have to do is to add a new <postprocessor> node with your postprocessor classpath in the XML file `ModernMT/src/textprocessing/src/main/resources/eu/modernmt/processing/postprocessor-default.xml` 

I hope this helps!

Andrea

**Comment by AndRossi** [comment] 2017-11-08 12:28
Hi @martinbrain, 

Since you are going to develop the post-processor by yourselves, I am closing this issue now.
Of course, if you need any help on the post-processor don't hesitate to re-open it :)

Andrea

**Comment by martinbrain** [comment] 2017-12-14 11:20
Hi Andrea,

Sorry to come back on this closed item but we struggled to make this work and I remembered your kind advice to re-open the ticket if we needed any help.  I wondered if you would be able to help us by providing an example?  

One pattern we are trying to correct is [number]% [material] - in the original post above I gave the example "100% cotton".  We often have these constructions in product descriptions, and occasionally in lists like "70% cotton, 25% viscose, 5% polyurethane".

Would you be able to show us an example of applying something to handle this in the Text Processor file?

Many thanks!
Matt

**Comment by AndRossi** [comment] 2017-12-20 15:35
Hi @martinbrain, 

I'm glad to help :)

As you have probably seen, pre-processing and post-processing are handled in MMT with a pipes-and-filters pattern. The pipelines are defined in files 
`ModernMT/src/textprocessing/src/main/resources/eu/modernmt/processing/preprocessor-default.xml`
and
`ModernMT/src/textprocessing/src/main/resources/eu/modernmt/processing/postprocessor-default.xml`
respectively, and as you can see they feature several <processor> nodes, each one referring to a specific class.

Those classes are the implementations of the `TextProcessor<Translation, Translation>` interface that I was referring to in my old answer, so they are all good examples for your case.

As you will see, each of those classes implements a `call(Translation translation, Map<String, Object> metadata)` method in which they apply transformations to a Translation object and return the transformed Translation.

I believe that you should follow the same pattern, creating a new class implementing `TextProcessor<Translation, Translation>` and making its `call` method apply the rules you need for "merging" tokens. For instance, you can have your postprocessor merge two consecutive tokens "100" and "%" in a single "100%" token.

I hope it is clearer now :)

Andrea

**Comment by AndRossi** [comment] 2018-01-03 15:55
Hi @martinbrain, 

I'm closing this issue for inactivity.

For any further doubt, or if you need us to develop a custom solution for you, please don't hesitate to contact us :)

Have a wonderful day!

Andrea

**Closed by AndRossi** 2018-01-03 15:55 UTC
