### ISSUE TITLE
Can SDLXLIFF be translated via command line, or only pure XLIFF 1.x files are accepted?

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#281] opened 2017-10-12 18:10 UTC
Hello,

MMT can translate XLIFF file, but I also noticed SDLXLIFF XML referenced 
https://github.com/ModernMT/MMT/blob/4468451720bd1045105909126fe8a9013575b068/cli/translation.py

Can SDLXLIFFS be translated via command line the same way as pure 1.x XLIFFs? If command line file will only look for XLF extension, can we trick MMT to process SDLXLIFF, with its file extension renamed to XLF?

Thanks
Mindaugas

**Comment by AndRossi** [comment] 2017-10-13 07:46
Hi @mindaugasDEV ,

SDLXLIFF should be accepted indeed, but we are not 100% sure that the script will handle them properly.
My advice is to try to translate your SDLXLIFF file on a local engine and check if the result shows any issues. 

If there are problems, or if you see room for improvements, don’t hesitate to tell us! :)

Best,
Andrea

**Comment by AndRossi** [comment] 2017-10-26 09:11
Hello @mindaugasDEV, 

In the end, did you encounter any problems with SDLXLIFF files?

Have a nice day,
Andrea

**Comment by mindaugasDEV** [comment] 2017-10-26 09:27
Hi, @AndRossi 

Thanks for reminding.
Well, I am not sure whether I have translated the file properly.

I followed advice in #277 to translate via command line and used 
./mmt translate --context <your context> --batch --xliff < myfile.xliff

However, there was no output file generated. It is by design? I noticed that in node.log there are translations, but it is a proper way to get output of the above batch command?

By the way, log file contains translations, but command line produced an error message: 
<ERROR Unexpected exception: Exception (u` HTTP request failed with code 400: http://localhost:8045/translate?source=en&target=lt`,)>

I hoped that command line will produce XLF or SDLXLIFF file with all strings translated and XML codes correctly kept intact.  Let me know how to get the file translated.

Best,
Mindaugas

**Comment by AndRossi** [comment] 2017-10-26 11:48
Hi @mindaugasDEV, 

I have made some tests based on your error message, and it seems that the XLIFF Translator had trouble if it encounters an empty `source` node in a XLIFF `trans-unit`. 
I have just pushed in `master` node a fix in the XLIFFTranslator. 
Now, if a source node is empty, the trans-unit will be correctly skipped.

Can you please update your code to the latest commit in `master` and check if your XLIFF file gets translated properly?

Thanks for your patience and support :)

Andrea

**Comment by mindaugasDEV** [comment] 2017-10-26 14:57
Thanks, @AndRossi 

Now the output was not giving any error message (which is good).
Instead, it showed in command line the XML code of the translated SDLXLIFF file.

It did not create output SDLXLIFF file, but showed in command line instead. Not useful in production.
I used command `sudo ./mmt translate -e NEURAL --batch --xliff < translations/IFU.sdlxliff`

Best,
Mindaugas

**Comment by AndRossi** [comment] 2017-10-26 15:09
Hi again @mindaugasDEV, 

Thanks for your feedback.
You are right: the XLIFF Translator does not create a new file - it just prints the result in console.
To obtain the result in an output file, you can run it this way:

`sudo ./mmt translate -e NEURAL --batch --xliff < translations/IFU.sdlxliff > /path/to/output.sdlxliff` 
 
I hope this helps!
Thanks for your patience and support.

Andrea

**Comment by AndRossi** [comment] 2017-10-30 09:37
HI @mindaugasDEV, 

Since this problem seems solved I'm closing this issue now.
However for any doubt or further problem, feel free to reopen it.

Have a nice day!
Andrea

**Comment by mzeidhassan** [comment] 2017-11-13 04:39
Hi @AndRossi ,

Sorry for reopening this issue again. I confirm that the command 

`sudo ./mmt translate -e default --batch --xliff < 13541_1_Description.docx.sdlxliff`

displays the translation just fine in the terminal

I tried using your command 

`sudo ./mmt translate -e default --batch --xliff < 13541_1_Description.docx.sdlxliff > /home/mlearner/Documents/output2.sdlxliff`

but the generated file cannot be opened either in Trados Studio 2015 or 2017.  Please see screen shot.

![neural_mmt_sdlxliff_error](https://user-images.githubusercontent.com/7589948/32709910-dafb7408-c83c-11e7-8b34-45b85a42726b.PNG)

Any idea?

Thanks,
Mohamed

**Comment by mzeidhassan** [comment] 2017-11-13 04:51
I noticed that the generated file has this at the top:

<?xml version='1.0' encoding='utf8'?>

Changing 'utf8" to 'utf-8' opens the file, but the translation doesn't appear in Studio. 

If I open the generated sdlxliff file in Notepad ++ for example, I see translations there. I am puzzled. 
Any idea why translation doesn't show up in the target column in Studio?

Thanks,
Mohamed Zeid

**Comment by AndRossi** [comment] 2017-11-13 13:52
Hello @mzeidhassan, 

Thanks for this report.
As for the utf8 problem: I have just committed into `master` branch a fix that should solve the problem.
The encoding that is now written in the xml node is now "UTF-8".

As for the problem with Studio: the only cause I can think about is that, for unknown reasons, the output file does not follow the correct SDLXLIFF structure. 
Can you please send me a working .sdlxliff file and your not working .sdlxliff file? 
(If the content of your files is private, you can just erase the content of the `source` and `target` nodes).
This way I can check if there are some differences in their xml structure.
 
Thank you for your patience and your support!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-14 01:01
Hi @AndRossi ,

I think you are right about the file structure. Kindly download the original file along with the mtranslated one from 
https://goo.gl/ukpuFC

Thanks again for your support!

Mohamed

**Comment by AndRossi** [comment] 2017-11-14 13:59
HI @mzeidhassan, 

Thanks for your files. I have checked them, and my SDL Studio (version 2015) manages to open the output file.
What SDL Studio version are you currently using? Maybe updating it can solve the issue.

Have a nice day!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-14 15:38
Hi @AndRossi, 

I used both SLD Studio 2015 and 2017. I believe I sent the changed output file 'changed utf8 to UTF-8", so yes, it opens at my end, but there is no translation showing up in Studio. Do you see Arabic translation in Studio after opening?

Thanks,
Mohamed

**Comment by AndRossi** [comment] 2017-11-14 16:38
Hello @mzeidhassan, 

I believe we have found the cause of this problem - it's an improvement in the XLIFF file format that we did not take into account. 

I will immediately implement a fix and let you know when it is ready as soon as possible.

Thank you again for your patience and your great support!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-14 20:36
This is great news, @AndRossi!

Glad that we found the issue and there is a fix for it. 

Please let me know when I can update my instance.

Thanks again for your amazing support and responsiveness!

**Comment by AndRossi** [comment] 2017-11-15 16:57
Hello @mzeidhassan, 

I have pushed to `master` branch a fix that should solve this problem.
I have tested it on SDL Studio 2017 and it seems to read all the translations fine.
Can you please check if this solves your issues? Thank you!

Have a nice day, 

Andrea

**Comment by mzeidhassan** [comment] 2017-11-16 04:08
Hi @AndRossi ,

It works perfect now. Thank you so much!

I have another question about batch translation and a suggestion/enhancement request.

Suppose I have a folder with a bunch of xliff files to translate.

Is there a command for batch translation of all xliff files in that particular folder?

As for the suggestion:

Is it possible that the translated file(s) will have the exact same source file name and maybe 'out' or 'output' is appended to it? As far as I understand now, you need to specify a path and a file name for the translated file? You can do this for one file, but if you are dealing with bunch files, it will be very challenging.

I also noticed an issue with files that has spaces in its name. If you try to translate a file that its name has spaces, something like that  "11-10-17 - Letter to client.docx.sdlxliff", I get this error:

`No such file or directory`


One last serious issue regarding Context Matches (CM) and 100% matches:

I noticed that MMT doesn't respect context matches and even locked segments in Trados Studio. This is a serious issue. It shouldn't touch these segments that has CM status or 100% matches . I am not sure about fuzzy matches. What do you think? Do you think it's safer to leave out any segment that has an existing translation in it? At least, the CM and 100% matches shouldn't be touched, I believe.

Please see screen shots (before and after). 

![before](https://user-images.githubusercontent.com/7589948/32873330-1ba7a22a-ca94-11e7-99c5-60f236e99427.PNG)
![after](https://user-images.githubusercontent.com/7589948/32873331-1bb9ce5a-ca94-11e7-8e22-44bcd4f1d434.PNG)

Thanks again!

Mohamed

**Comment by AndRossi** [comment] 2017-11-16 12:34
Hi again @mzeidhassan, 

I'm glad now it works well!

I understand the problem with Context Matches and 100% matches.  
I have just released in `master` branch a fix that should lead to ignore those segments.

I have also written a xliff translate script. You can launch it on a specific folder like this:

```bash
<your_mmt_home>/extras/translate_xliff.sh /path/to/your/folder
```

And it will translate all your files, putting the outputs in a separate subfolder in your folder.

You can also pass a single file instead of a folder.
```bash
<your_mmt_home>/extras/translate_xliff.sh /path/to/your/file
```

In this case the output file will be put in the same folder as the input file. 


As for files with spaces in their name you should be able to handle them using double quotes.
For instance:

```bash
<your_mmt_home>/extras/translate_xliff.sh "/path/to/11-10-17 - Letter to client.docx.sdlxliff"
```

Let me know if these solutions work fine  :)

Have a nice day! 

Andrea

**Comment by mzeidhassan** [comment] 2017-11-17 17:24
Hi @AndRossi 

I test this new script, but it throws this error:

`translate_xliff.sh: Syntax error: word unexpected (expecting ")")`

I also noticed that when it's running at first, the machine almost freezes up and the cursor turns into a cross. Not sure why?

Thanks,
Mohamed

**Comment by AndRossi** [comment] 2017-11-20 11:24
Hi @mzeidhassan, 

I'm sorry about that - there was a typo in my script.
I have fixed it now and I have pushed the fix into `master` so it should work fine. 
Please let me know if it works as it should on your side too.

Thanks for your patience!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-20 20:08
Hi @AndRossi,

Thanks for taking the time to look into this. I did "git pull origin master", but running the script takes forever and freezes the machine. Once I try to open a folder for example while it's running, it crashes with this error:

`sh translate_xliff.sh /home/mlearner/ModernMT/xliff_trans`

Not sure why this is happening? Should I put the folder 'xliff_trans' outside of MMT directory?

Please let me know if there is any log ouput I need to pass it on.

Thanks,
Mohamed

**Comment by AndRossi** [comment] 2017-11-21 08:45
Hi again @mzeidhassan, 

I think I have found the cause of the  
`translate_xliff.sh: 6: translate_xliff.sh: Syntax error: word unexpected (expecting ")")` problem.

It should depend on the fact that my script is written in python. 
Therefore, even if the bash can run it with `./` command, `sh` does not recognize its syntax and complains. The fact that my file had `.sh` extension was definitely misleading: sorry about that!  
I have now removed that extension, so in the latest `master` commit the file path is just `<your_mmt_home>/extras/translate_xliff`.

You can run it like this from your MMT home:
`extras/translate_xliff /path/to/your/xliff/folder` 

I hope this solves the problem!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-22 18:34
Thanks @AndRossi ! I confirm that this works perfectly now. It takes a long time though to translate 3 small files. I am not sure if there is anything we can do speed it up, but I thought I should let you know.

By the way, do you have metrics of how many words per second can be translated using MMT API and with which specs?

One last thing:

If I have multilingual engine, how can I pass the language combination parameters? Say, I want to translate from EN>AR and another folder from EN>ES. Is there a way to do this?

Thanks again for your continuous support!

Mohamed

**Comment by AndRossi** [comment] 2017-11-22 19:07
Hi @mzeidhassan,

It's great it works fine now!
You can check the translation speed with `./mmt evaluate`.

As for the language combination in `translate_xliff`: unfortunately we still have not upgraded the python interface to support multilingual engines, so at the moment you can only translate using the first language pair that your engine supports. 
We will fix this inconvenience as soon as possible :) 

Andrea

**Comment by mzeidhassan** [comment] 2017-11-27 22:00
Thanks @AndRossi ! Please let me know when the fix is available.

**Comment by davidecaroselli** [comment] 2017-12-02 10:19
Hi @mzeidhassan 

I've just created a new issue #316 in order to distinguish between the XLIFF bug that has been solved and the new-feature request.

Thanks for you support!
Davide

**Closed by davidecaroselli** 2017-12-02 10:19 UTC
Labels: bug
