### ISSUE TITLE
Empty TUs in TMX files and unclear error message

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#320] opened 2017-12-05 22:04 UTC
Hello MMT team,

I am reporting this just in case you want to make the error message more meaningful and helpful.

I was training an engine and some of the TMX files had wrong date formats and some empty Translation Units "TUs". 

In the case of 'wrong date format', MMT did a great job and explained the cause of the error and in which file it exists. So, this was an easy fix for me.

On the other hand, the error message that I got because there were some empty strings in the TMX files, was not clear at all. Here it's:

> 2017-12-05 11:17:52,135 [INFO] - Training started: engine=enzh, bilingual=18, monolingual=0, langpair=en-zh
2017-12-05 11:17:52,135 [DEBUG] - Shell exec: nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits --id=0
2017-12-05 11:17:52,144 [INFO] - Training step "clean_tms" (1/9) started
2017-12-05 11:17:52,144 [DEBUG] - Shell exec: java -Xmx43434m -cp /opt/orcchinese/build/mmt-2.0.2.jar -Dmmt.home=/opt/orcchinese -Djava.library.path=/opt/orcchinese/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t zh --filters normalize punctuation odd_sentences drafts sentence_length --output /opt/orcchinese/runtime/enzh/tmp/training/clean_corpora --input /opt/orcchinese/examples/data/train
2017-12-05 11:17:52,337 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-12-05 11:18:32,711 [INFO] - Training step "clean_tms" completed in 40 s
2017-12-05 11:18:32,711 [INFO] - Training step "create_db" (2/9) started
2017-12-05 11:18:32,711 [INFO] - Training step "create_db" completed in 0 s
2017-12-05 11:18:32,711 [INFO] - Training step "preprocess" (3/9) started
2017-12-05 11:18:32,711 [DEBUG] - Shell exec: java -cp /opt/orcchinese/build/mmt-2.0.2.jar -Dmmt.home=/opt/orcchinese -Djava.library.path=/opt/orcchinese/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t zh --output /opt/orcchinese/runtime/enzh/tmp/training/preprocessed_corpora --input --dev /opt/orcchinese/engines/enzh/data/dev --test /opt/orcchinese/engines/enzh/data/test
Exception in thread "main" org.apache.commons.cli.MissingArgumentException: **Missing argument for option: input**
	at org.apache.commons.cli.DefaultParser.checkRequiredArgs(DefaultParser.java:211)
	at org.apache.commons.cli.DefaultParser.handleOption(DefaultParser.java:599)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:402)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:371)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at eu.modernmt.cli.TrainingPipelineMain$Args.<init>(TrainingPipelineMain.java:56)
	at eu.modernmt.cli.TrainingPipelineMain.main(TrainingPipelineMain.java:78)
2017-12-05 11:18:32,776 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/opt/orcchinese/cli/mmt/engine.py", line 480, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/opt/orcchinese/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/opt/orcchinese/cli/mmt/engine.py", line 565, in _preprocess
    log=log)
  File "/opt/orcchinese/cli/mmt/processing.py", line 119, in process
    shell.execute(command, stdout=log, stderr=log)
  File "/opt/orcchinese/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /opt/orcchinese/build/mmt-2.0.2.jar -Dmmt.home=/opt/orcchinese -Djava.library.path=/opt/orcchinese/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t zh --output /opt/orcchinese/runtime/enzh/tmp/training/preprocessed_corpora --input --dev /opt/orcchinese/engines/enzh/data/dev --test /opt/orcchinese/engines/enzh/data/test' failed with exit code 1

So, I hope MMT can point to the file that is causing the issue and maybe say something more meaningful related to the error itself and the lines where the missing TUs are.

I thought I should let you know and in case someone else is having the same error, then they know what is the reason. I hope this helps.

Thanks again in advance!

Mohamed Zeid

**Comment by AndRossi** [comment] 2017-12-06 09:48
Hi @mzeidhassan,

Thanks for reporting this.

I believe that the problem, though, is not caused by the empty TU in your TMX.
If that was the case, in fact, the error in `training.log` file would look like this:

```bash
Caused by: javax.xml.stream.XMLStreamException: Missing source text in <tu> element at line 25
        at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.readTu(TMXPairReader.java:109)
        at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.read(TMXPairReader.java:47)
        at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:52)
```


I believe that your error is raised in a much more peculiar scenario: it only takes place when
* you use at least one TMX file in the training set;
* in all your training set no valid segments can be found (i.e. no segments with the correct source-target language combination);

I think that this problem "overlapped" with you having an empty TU: When you fixed your empty TU, it became a valid segment and so it solved the problem, but the empty TU, in itself, was not the real issue.

I have now pushed into `master` branch a commit that should give more detailed errors in cases like this:

```
=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > zh

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 0s)
INFO: (2 of 6) Corpora pre-processing...                              ERROR Corpus not found: Could not find any valid en -> zh segments in your input.
```

I think it is much better now :)  
Since this issue is solved I'm closing it now.  
Of course do not hesitate to re-open it if you need any further help :)

Thank you again for your great support!

Have a wonderful day,

Andrea

**Closed by AndRossi** 2017-12-06 09:48 UTC
