### ISSUE TITLE
Strange truncation behavior with a particular sentence

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#305] opened 2017-11-21 22:27 UTC
Hello MMT team,

I am testing MMT with some online automotive text and translating the following paragraph via the REST API and for some reason, the last sentence `There are 7 volume settings` doesn't get translated. 

Here is the complete paragraph:

> This feature utilizes the vehicle’s built-in microphone to amplify the driver’s voice through the rear speakers. To activate this feature, select “Driver Easy Speak” from the Apps screen on the audio unit. The feature must be turned on every time you enter the vehicle, and automatically turns off when any door (including the liftgate) is opened.  There are 7 volume settings.

Initially, I thought this was a character limitation issue, but I entered a larger text  and it was completely translated. 

Also, when I just enter 'There are 7 volume settings', it gets translated as well.  It's doesn't get translated only within the whole paragraph. 

I am not sure what is causing such truncation behavior? Any idea?

Have you experienced a similar issue? I will test more with different strings and see how it goes, but I thought I should ask here, in case you are aware of this issue. 

Thanks,
Mohamed

**Comment by EtienneAb3d** [comment] 2017-11-22 08:40
MMT will certainly confirm this: you need to send sentences, because MMT is trained to translate sentences, and is not supposed to get paragraphs with multiple sentences to translate.

**Comment by AndRossi** [comment] 2017-11-22 13:47
Hello @mzeidhassan, 

I think there are two main possibilities: 
- either there is a bug in MMT that leads to ignore that last sentence. In this case, it is ignored *before* it is sent to the neural decoder.
- or it is the neural decoder that decides to ignore it. As @EtienneAb3d mentioned, in fact, our neural decoder has been trained and designed to just handle single sentences.  
Therefore it is possible that text blocks with multiple sentences result in weird behaviours like this one (in this case you just need to split your text in correspondence of your full stops `.`) .

Fortunately, it is quite easy to check whether we are in the former scenario or in the latter.
- Stop your engine with `./mmt stop`, and start it again with a more verbose logging strategy using `./mmt start -e <your_engine_name> -v 3`
- Try to translate your period again with this command: 
```bash
curl -X GET http://localhost:8045/translate \
     -d "source=<your_src_lang>" \
     -d "target=<your_trg_lang>" \
     -d "q=This feature utilizes the vehicle’s built-in microphone to amplify the driver’s voice through the rear speakers. To activate this feature, select “Driver Easy Speak” from the Apps screen on the audio unit. The feature must be turned on every time you enter the vehicle, and automatically turns off when any door (including the liftgate) is opened. There are 7 volume settings." \
     | python -mjson.tool
```
- you can check which input was passed to the decoder in file `<your_mmt_home>/runtime/<your_engine_name>/logs/node.log`. This way it is easy to check if the missing sentence was sent to the decoder or not. If it was not there is definitely a bug.

I hope this helps! :)

Please let me know the result of this check, or just send me the the log file so I can check that for you. 

Have a wonderful day!
Andrea

**Comment by mzeidhassan** [comment] 2017-11-22 19:31
Thanks @AndRossi 

Here is what I see in the node.log. Again, that particular sentence was not translated for some reason. I don't know why. 

> 2017-11-22 12:25:10,406 INFO  eu.modernmt.rest.RESTServer$Router [qtp210737063-94] REST Request (a05203c4-16c8-451b-a5dd-5f21bb86708e): GET /translate?source=en&target=ar&q=This feature utilizes the vehicle’s built-in microphone to amplify the driver’s voice through the rear speakers. To activate this feature, select “Driver Easy Speak” from the Apps screen on the audio unit. The feature must be turned on every time you enter the vehicle, and automatically turns off when any door (including the liftgate) is opened. There are 7 volume settings.
2017-11-22 12:25:10,406 DEBUG eu.modernmt.rest.RESTServer$Router [qtp210737063-94] Executing REST action Translate
2017-11-22 12:25:10,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:10,859 DEBUG com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Invocations:1 timeouts:0 backup-timeouts:0
2017-11-22 12:25:11,731 DEBUG eu.modernmt.decoder.neural.execution.NativeProcess [hz._hzInstance_1_eu.modernmt.cached.thread-7] Received translations: [{"text":"تستخدم هذه الميزة الميكروفون المدمج للسيارة لتضخيم صوت السائق من خلال مكبرات الصوت الخلفية . لتنشيط هذه الميزة ، حدد \" السائق Easy Speak Speak \" من شاشة \" التطبيقات \" على الوحدة الصوتية . يجب تشغيل هذه الميزة في كل مرة تقوم فيها بالدخول إلى السيارة ، ويتم إيقاف تشغيلها تلقائياً عند فتح أي باب ( بما في ذلك الباب الخلفي ).","alignment":[[1,1,2,4,6,7,8,9,11,13,14,14,16,17,17,18,19,21,22,23,24,25,26,27,28,28,29,30,32,32,33,34,34,36,37,38,40,40,41,43,45,45,46,48,48,48,50,50,51,53,54,54,55,56,58,58,59,60,60,60,62,62,63,65],[1,2,0,5,4,3,6,6,8,7,9,10,13,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,28,29,27,30,31,33,32,34,37,38,35,36,39,40,41,42,43,44,45,46,47,51,48,49,50,52,54,55,56,57,58,59,60,61,62,53]]}]
2017-11-22 12:25:11,731 INFO  eu.modernmt.decoder.neural.NeuralDecoder [hz._hzInstance_1_eu.modernmt.cached.thread-7] Translation of 73 words took 1.322s
2017-11-22 12:25:11,734 INFO  eu.modernmt.rest.RESTServer$Router [qtp210737063-94] REST Response (a05203c4-16c8-451b-a5dd-5f21bb86708e): 200 {"status":200,"data":{"decodingTime":1322,"translation":"تستخدم هذه الميزة الميكروفون المدمج للسيارة لتضخيم صوت السائق من خلال مكبرات الصوت الخلفية. لتنشيط هذه الميزة ، حدد “السائق Easy Speak Speak” [...]
2017-11-22 12:25:11,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:12,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:13,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:14,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:14,860 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Broadcasting operation heartbeats to: 1 members
2017-11-22 12:25:15,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:16,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:17,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:18,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:19,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:19,872 TRACE com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer [hz._hzInstance_1_eu.modernmt.IOBalancerThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] No imbalance has been detected. Max. events: -9223372036854775808 Min events: 0.
2017-11-22 12:25:19,872 TRACE com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer [hz._hzInstance_1_eu.modernmt.IOBalancerThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] No imbalance has been detected. Max. events: -9223372036854775808 Min events: 0.
2017-11-22 12:25:20,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:21,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:22,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:23,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:24,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:25,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:26,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:27,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:28,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:29,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:29,860 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Broadcasting operation heartbeats to: 1 members
2017-11-22 12:25:30,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:31,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:32,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:33,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:34,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:35,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:36,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:37,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:38,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:39,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:39,873 TRACE com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer [hz._hzInstance_1_eu.modernmt.IOBalancerThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] No imbalance has been detected. Max. events: -9223372036854775808 Min events: 0.
2017-11-22 12:25:39,873 TRACE com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer [hz._hzInstance_1_eu.modernmt.IOBalancerThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] No imbalance has been detected. Max. events: -9223372036854775808 Min events: 0.
2017-11-22 12:25:40,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:41,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:42,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:43,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:44,859 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Scanning all invocations
2017-11-22 12:25:44,860 TRACE com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [hz._hzInstance_1_eu.modernmt.InvocationMonitorThread] [127.0.1.1]:5016 [eu.modernmt] [3.7.5] Broadcasting operation heartbeats to: 1 members

**Comment by AndRossi** [comment] 2017-11-23 08:50
Hello @mzeidhassan, 

From your log I can see that "There are 7 volume settings." was actually received  by the MMT instance, so it should have been sent to the decoder without problems.

So I believe that this is exactly the case that @EtienneAb3d had described in his comment (the scenario 2 in my previous answer): the neural decoder is used and trained to receive single sentences, and when a complex text block with many multiple sentences is sent, it may show an unexpected behaviour.

So in order to get your engine to translate multiple sentences, you need to send them separately.

I'm glad we have shedded light on this!
Please let me know if you need any further clarifications on this :)

Have a nice day!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-25 18:52
Thanks @AndRossi for your reply. I see now, but what is strange here is that larger paragraphs could be translated without no problem, so not sure why this particular sentence in this string was not translated. That said, thanks again for looking into this and thanks @EtienneAb3d for your help! 

Have a great weekend!

**Comment by AndRossi** [comment] 2017-11-27 08:30
Yeah, I understand your point: I seems really anti-intuitive that long paragraphs are kept untouched whereas short ones get truncated :)
However, I believe this is quite possible. My suspicion is that, since full stops usually correspond to input end in training data, the model really does not know how to handle a full stop that is in the middle of a text block. 
So depending on what the rest of the input looks like, in some "unlucky" cases it may decide to truncate the rest of the paragraph, while in other cases it may decide to translate it nevertheless.

In general, when you give a neural network data that differ (even just a bit) from what it was trained on, weird behaviours like this are possible :)

Since the problem was clarified I am closing this issue now; as usual, if you need any more details on this please feel free to re-open it.

Have a nice day!

Andrea

**Comment by AndRossi** [comment] 2017-11-27 13:25
I'd like to reword a bit my previous comment to explain it better.

In general, neural networks are pretty good at generalizing, and at handling cases that are not featured in the training set. This is one of the reasons why neural networks are employed so much in translation tasks. 
In fact, even if MMT itself is not designed to accept text blocks with multiple sentences, as you noticed it manages to translate them correctly in the large majority of cases :)

However, with these premises, it is possible to have rare unlucky cases; in your scenario, the internal model decides that, for that text block only, the translation is better cutting off the output of the final sentence.

In any case we are thinking to implement a sentence segmentation feature.  
In this way, when a user submits the translation of a text block with multiple sentences, MMT should transparently identify the sentences and translate them separately.  
It should solve problems like this one!

I'm reopening this issue for this reason. I'll keep you updated on this feature :)

Thank you again for your great support!

Andrea

**Comment by mzeidhassan** [comment] 2017-11-27 21:58
Thanks @AndRossi for your latest answer :-) This is great to know. This will be a great feature indeed. Yes, please let me know when it's available. Thanks again for your support!

**Comment by davidecaroselli** [comment] 2017-12-07 17:23
Hi @mzeidhassan 

starting from the latest master commit https://github.com/ModernMT/MMT/commit/09981f7d35c366d5446e50a65d23c157ad90fabc sentence segmentation feature is available for **neural engines**. Enjoy! :)

**Closed by davidecaroselli** 2017-12-07 17:23 UTC
Labels: feature-request

**Comment by AndRossi** [comment] 2017-12-07 17:34
Hi @mzeidhassan, 

just a detail: after updating MMT to commit 09981f7 you will probably need to upgrade your older 2.x engines.

You can find all information on how to upgrade them in #322 :)

Have a nice weekend!

Andrea

**Comment by mzeidhassan** [comment] 2017-12-08 04:49
Thank you so much for the update, @davidecaroselli and @AndRossi ! Have a wonderful weekend ahead!
