### ISSUE TITLE
Error while creating new engine for new language

### ISSUE THREAD

**Issue by chathurangamdk** [ModernMT/MMT#335] opened 2018-01-15 06:41 UTC
I try to create an engine English -> Bahasa(Indonesian). I get an error saying "corpus not found". Installation is done using source itself and succeeded in en->it (demo) translation. My OS is Ubuntu 16.04 Desktop. 
Can you help me to resolve this?

-------------------- **terminal out** ------------------------------
./mmt create en id examples/data/en_id/

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > id

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 1s)
INFO: (2 of 6) Corpora pre-processing...                              ERROR Corpus not found: Could not find any valid en -> id segments in your input.

--------------------  **training.log**  ------------------------------
2018-01-15 14:17:11,592 [INFO] - Training started: engine=default, bilingual=1, monolingual=0, langpair=en-id
2018-01-15 14:17:11,594 [INFO] - Training step "clean_tms" (1/9) started
2018-01-15 14:17:11,595 [DEBUG] - Shell exec: java -Xmx8993m -cp /home/user/ModernMT/build/mmt-2.2.jar -Dmmt.home=/home/user/ModernMT -Djava.library.path=/home/user/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t id --output /home/user/ModernMT/runtime/default/tmp/training/clean_corpora --input /home/user/ModernMT/examples/data/en_id
2018-01-15 14:17:12,002 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2018-01-15 14:17:12,910 [INFO] - Training step "clean_tms" completed in 1 s
2018-01-15 14:17:12,911 [INFO] - Training step "create_db" (2/9) started
2018-01-15 14:17:12,911 [INFO] - Training step "create_db" completed in 0 s
2018-01-15 14:17:12,911 [INFO] - Training step "preprocess" (3/9) started
2018-01-15 14:17:12,912 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/user/ModernMT/cli/mmt/engine.py", line 481, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/user/ModernMT/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/user/ModernMT/cli/mmt/engine.py", line 564, in _preprocess
    (self._engine.source_lang, self._engine.target_lang))
CorpusNotFoundInFolderException: Could not find any valid en -> id segments in your input.

**Comment by AndRossi** [comment] 2018-01-15 09:26
Hi @chathurangamdk, 

Thanks for trying MMT!

In its cleaning phase, MMT filters out low quality segments from your input files because they may affect the overall quality of the resulting engine; the error you are experiencing is caused by the fact that, after cleaning, no en -> id were left in your input files.

Therefore, my first suggestion would be to use a higher quality corpus. If you don't have one, you can probably fine some good corpora here: http://opus.nlpl.eu/
 
Another possibility is to skip the cleaning phase. 
MMT allows to manually specify which steps to run during `./mmt create`, so you can just specify all steps but the cleaning one.

```bash
./mmt create en id examples/data/en_id/ -s create_db \
preprocess \
train_context \
train_aligner \
write_config \
train_tm \
train_lm \
write_moses_config
```
(the cleaning step that we are skipping this way would be `clean_tms`).

I would not advice that, though, because as I said the cleaning phase has great effects on the resulting engine quality.

I hope this helps! Please let me know if you manage to train your engine :)

Have a nice day!

Andrea

**Comment by chathurangamdk** [comment] 2018-01-16 03:13
Hi Andrea 
Thank you for your quick reply. 

Actually I'm using opus.nlpl.eu corpora for train the engine. It is en -> id Tatoeba moses coropa. Still gives me the same error.

When I use the **flagged** command as you said, it worked fine. So I managed to train the engine with that. Thanks a lot for your guidance. Really appreciated. 👍 

Have a nice day!
Kasun.

**Comment by AndRossi** [comment] 2018-01-16 13:37
Hi @chathurangamdk, 

I have investigated this problem and I have found out that it depends from a sort-of-buggish behaviour in the OpenJDK Locale class.

For some languages that have changed their ISO code for historical reasons, the OpenJDK Locale class still uses the old codes in some methods. Indonesian is among those languages - that's why this issue is raised. 

We are working to fix this right now, so I'll let you know as soon as the solution is ready :)

Thanks for your patience!

Andrea

**Comment by AndRossi** [comment] 2018-01-17 16:24
Hi again @chathurangamdk, 

It was quite harder than we expected, but you can find a fix for this issue in our `master` branch :)
To update your MMT installation just run these commands one by one starting from your MMT home:
```bash
git pull origin master
cd src
mvn clean install
```

After that, your engine creation should run fine.

Please let me know if you manage to train your engine now :)
Thanks again for your patience!

Have a nice day,

Andrea

**Comment by AndRossi** [comment] 2018-01-22 09:51
Hi @chathurangamdk,
I'm closing this issue due to inactivity. After the fix I have successfully trained an engine using the Tatoeba corpus,  so I believe the problem was solved. 

If you encounter this issue again, or if you have any further problem or doubt, though, do not hesitate to re-open it! 

Have a nice day :)

Andrea

**Closed by AndRossi** 2018-01-22 09:51 UTC
