### ISSUE TITLE
Ascendant compatibility problem ? Bug in latest version ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#307] opened 2017-11-25 10:10 UTC
One month ago I installed MMT from sources (after the thread overload problem). I built a statistical  FR->EN model. It is still properly working with this MMT version.
Yesterday, I re-installed MMT from sources, on an other machine. This model is no more working properly : very fastly, it provides with an untranslated sentence:

> curl  'http://localhost:8045/translate?q=Ceci%20est%20une%20phrase%20en%20français&target=en&source=fr'
> {"status":200,"data":{"decodingTime":334,"translation":"Ceci est une phrase en français","sourceWordCount":6,"targetWordCount":6}}  

Is this simply an ascendant compatibility problem, or it there a bug in latest code ?

**Comment by EtienneAb3d** [comment] 2017-11-25 10:35
I tried to copy the older MMT to the new machine. I first got explicit link error on some ".so" libs. I solved them with few "ln -s" commands. 
But, I now get this strange, not explicit, error:
2017-11-25 11:29:59,359 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
java.lang.UnsatisfiedLinkError: eu.modernmt.decoder.phrasebased.NativeLogger.initialize()V
	at eu.modernmt.decoder.phrasebased.NativeLogger.initialize(Native Method)
	at eu.modernmt.decoder.phrasebased.MosesDecoder.<clinit>(MosesDecoder.java:38)
	at eu.modernmt.engine.impl.PhraseBasedEngine.<init>(PhraseBasedEngine.java:32)
	at eu.modernmt.engine.Engine.load(Engine.java:72)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:319)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)

**Comment by davidecaroselli** [comment] 2017-11-25 17:13
Hi @EtienneAb3d ,

no, this is definitely an issue: the two version of MMT should be fully compatible. So first the problem with the libraries linking: this can be caused by a "messy" build folder. I'll suggest to:

1. Pull the latest master branch: `git pull origin master`
2. Clean your build folder: `rm -rf build/*`
3. Re-compile dependencies: `cd vendor ; ./compile ; cd ..`
4. Re-compile mmt: `cd src ; mvn clean install ; cd ..`

Now, on the verbatim translations problem: I remember I had the same issue time ago and it was a problem of a C library we use that was compiled in different ways and wasn't able to properly read the phrase-table model (and lm model) anymore. At that time the problem was due a dependecy called `libsnappy-dev`: I trained the engine with MMT built with this library and then tried to run with another MMT installation built without this lib.

So what I suggest you is to try compile MMT first with snappy:

```
sudo apt-get install libsnappy-dev
cd src
mvn clean install
```

Then try to run your engine, if this didn't solve the problem, then try with building MMT without that library:
```
sudo apt-get remove --purge libsnappy-dev
cd src
mvn clean install
```

And finally, try again booting the engine and translate the sentence.

Let me know if this solved the issue!

**Comment by EtienneAb3d** [comment] 2017-11-26 09:27
With or without libsnappy-dev, it doesn't translate...
:-(

**Comment by EtienneAb3d** [comment] 2017-11-26 09:38
I tried to rebuild the older version on this machine, without updating to the latest master: it works ! There is thus, at least on this machine, a difference between the 2 releases.

**Comment by davidecaroselli** [comment] 2017-11-27 08:13
ok, can you please send me the exact commit of the working version? I'll try to replicate the issue and debug it.
Thanks.

**Comment by EtienneAb3d** [comment] 2017-11-27 12:52
Link sent by email.
;-)

**Comment by davidecaroselli** [comment] 2018-02-16 11:32
Hi @EtienneAb3d 

I'm sorry, we had not the chance to dig more on this issue, and we are not expecting to have time to investigate further on this, because our main focus is now neural.

For this reason, I'm closing the issue. If you have the time to investigate on this, I will be happy to support you: in that case, please feel free to re-open this issue.

Thanks,
Davide

**Closed by davidecaroselli** 2018-02-16 11:32 UTC
Labels: bug

**Comment by patul55** [comment] 2018-10-10 11:59
atul@atul-HP-ProBook-440-G2:~/ModernMT$ ./mmt create en it examples/data/train --train-steps 6 -e Atul
An engine named "Atul" already exists, are you sure you want to overwrite it? [y/N] y

=========== TRAINING STARTED ===========

ENGINE:  Atul
CORPORA: 3 corpora
LANGS:   en > it

WARNING: No GPU for Neural engine training, the process will take very long time to complete.

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 2s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Aligner training...                                     DONE (in 3s)
INFO: (4 of 6) Preparing data...                                      
ERROR Unexpected exception: None

Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 143, in main_create
    builder.build()
  File "/home/atul/ModernMT/cli/mmt/engine.py", line 556, in build
    self._build(resume=False)
  File "/home/atul/ModernMT/cli/mmt/engine.py", line 629, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/atul/ModernMT/cli/mmt/engine.py", line 428, in __call__
    self._f(*args, **kwargs)
  File "/home/atul/ModernMT/cli/mmt/engine.py", line 760, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols)
  File "/home/atul/ModernMT/cli/mmt/engine.py", line 153, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/atul/ModernMT/cli/libs/osutils.py", line 57, in shell_exec
    raise ShellError(str_cmd, return_code, stderr_dump)
cli.libs.osutils.ShellError: Command 't2t-datagen --t2t_usr_dir /home/atul/ModernMT/build/lib/t2t --data_dir=/home/atul/ModernMT/runtime/Atul/tmp/training/neural_train_data/data --tmp_dir=/home/atul/ModernMT/runtime/Atul/tmp/training/neural_train_data/tmp --problem=translate_mmt' failed with exit code -11
