### ISSUE TITLE
Confusing documentation of the REST Api

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#215] opened 2017-01-17 14:25 UTC
Hello guys,
My understanding is that Domain refers to the name of a Dataset linked to a Domain.
Context refer to a "string of characters" that could better qualify the source sentence we want to translate.

Therefore:
Get / Context returns a domain that suits the best the "context" string sent to the API.
the doc says in the example: output = context

Also don't you think that it would be usefull to translate by giving a domain (instead of context) to get the best suited target sentence ?

**Comment by davidecaroselli** [comment] 2017-01-17 15:58
Hi @vince62s ,

we could definitely improve our documentation ;)
So, what you said about the Domain is correct: a Domain is an entity inside MMT that has a name, an id, and it's basically a container for parallel text.
In an domain you can add content via API, both single sentence pair (source, translation) or whole TMX for example.

During the translation we use the "context" in order to better identify the origin of the source sentence: the context can be calculated, for example, analyzing the whole document in which the source sentence is, or a bunch of lines that come before the source sentence itself.

When you pass such information to "GET /context" API, the text is analyzed and a **set** of best-matching domains is returned together with a score for each domain. That context is then used to actually translate the source sentence.

> Also don't you think that it would be usefull to translate by giving a domain (instead of context) to get the best suited target sentence ?

Yes, in fact "GET /translate" also accept `context_weights` parameters where you can pass directly the context to be used.
If for example you want to force MMT to translate with just one domain, and that domain has id 3, you can invoke translate like the following:
```
curl 'http://localhost:8045/translate?q=This%20is%20an%20%3Cb%3Eexample%3C%2Fb%3E&context_weights =3:1.0' | python -mjson.tool
```

That is `context_weights` set to `3:1.0` - only domain `3` with maximum weight of `1.0`.

Where do you think we can improve the documentation in order to make all this more clear to the readers?

**Comment by vince62s** [comment] 2017-01-17 16:09
For instance just your last point. shouldn't context_weights be renamed domain_weights ?

also here:
https://github.com/ModernMT/MMT/wiki/API-Documentation
Context Guessing
GET /context
The Context API returns an array of the top domains matching the provided content. For each domain you obtain the consine similarity between the given context, and that domain.
Example
    Input:
        Text - "Mr President"
    Output:
        Context - europarl (0.13375875), ibm (0.008800022)

That last line should say Domain

**Comment by davidecaroselli** [comment] 2017-01-17 16:50
ok so the problem is the lack of an intermediate entity: the `Context Vector`.
When MMT analyzes a context (i.e. the string you pass to /translate API), it outputs the `Context Vector` that is, a vector containing the scores for the best-matching domains given the context text.

So in `/translate`  API you should be able to pass `context_vector` and not context_weights. And the Context API endpoint is `GET /context-vector` because you're creating the context vector from a string or a document (the context).

We will probably change this in the next release and of course we will update the documentation as well!

Thanks for the contribution!

**Comment by vince62s** [comment] 2017-01-17 17:41
I am not sure to understand your comment.
I think there are 2 different use case.
The first one is the one described in the doc right now. You give a "string" as a context and it will match the best ratios between domain.
The second use case is to give directly some weights as you say, but to me they should be called "domain_weights" because they are related to domains, not contexts.
Am I clear ?

**Comment by davidecaroselli** [comment] 2017-01-17 18:03
Sorry, I've been too hasty, and I did not explain well what I meant.
In the MMT team we have this concept of *Context Vector*, this is in fact a vector that associates a score to each relevant domain; its content is, in fact, what you call domain weights.

The "full" story is:
1. MMT analyze the context string with the context analyzer.
2. The result of the context analyzer is the *Context Vector*.
3. The *Context Vector* is then used to adapt the translation output.

So you can let `/translate` calculate the *Context Vector* for you, simply passing the `context` to the API, or you can pre-calculate the *Context Vector* with the `/context` API and then passing it directly to the `/translate`API. This second case can improve translation speed when you plan to do multiple translation with the same context.

So I would like to keep this concept for consistency with the MMT nomenclature. Of course I need to explain definitely better this 3-step translation process in the documentation because, as you pointed out, it is currently a little bit confusing.

Hope this explained a little bit more my previous post.
Cheers.

**Comment by vince62s** [comment] 2017-01-17 19:10
I get it.
I think the main point for an end user will be to specify a domain. Use case: we train an engine with 1 dataset "Generic" 1 dataset "Medical" 1 dataset "Financial".
I understand this vector thing. So the doc need to explain that the translation that belongs to the "Medical" domain needs to be attached to a context vector "50% 50% 0%"
Thanks for the clarification.

**Comment by davidecaroselli** [comment] 2017-01-20 14:26
I've have just completed a huge Documentation refactoring, I hope this could help explain better how MMT works and all the available public APIs.

I close this issue for the moment but please, if you have any other suggestions, re-open it os create new documentation issues.

Thanks!

**Closed by davidecaroselli** 2017-01-20 14:26 UTC
Labels: enhancement, question
