### ISSUE TITLE
MMT engine doesn't start properly

### ISSUE THREAD

**Issue by mtresearcher** [modernmt/MMT#457] opened 2019-04-01 17:50 UTC
```
ubuntu@38c7e6454d7e:~/mmt$ ./mmt start -e train-full-en-es
Starting MMT engine 'train-full-en-es'... OK
Loading models... OK

The MMT engine 'train-full-en-es' is ready.

You can try the API with:
	curl "http://localhost:8045/translate?q=world&source=en&target=it&context=computer" | python -mjson.tool
```

```
ubuntu@38c7e6454d7e:~/mmt$ ./mmt status
[Engine: "train-full-en-es"]
    REST API:   stopped
    Cluster:    stopped
    Datastream: stopped
    Database:   stopped
```

```
ubuntu@38c7e6454d7e:~/mmt$ ./mmt translate -e train-full-en-es < test

ERROR Illegal State: MMT engine 'train-full-en-es' is not running.
Start it with "./mmt start"
You can check the status of your engines with "./mmt status"
```

How did I train? 
I let the training running for a ~4 days, then SIGINT the t2t-trainer, then MMT didn't pack the model. So, I ran the training again with resume option and then SIGINT which triggered the packing step. 

Now, I am trying to start MMT engine and it says all ok at `./mmt start` stage but when I look at the `./mmt status` the engine is not running. What could be the problem here? How can I use the packed model for translation?

**Comment by mtresearcher** [comment] 2019-04-01 18:04
Here's the log from `./mmt start`. It says `Native decoder process on GPU 3 failed to start` 
I have four GPUs on this p3 machine, so working with GPU 3 shouldn't be a problem. 

```
2019-04-01 17:55:36,990 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2019-04-01 17:55:38,004 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.747s
2019-04-01 17:55:38,159 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2019-04-01 17:55:38,181 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2019-04-01 17:56:08,252 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 30s
2019-04-01 17:56:08,457 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process on GPU 0 is starting
2019-04-01 17:56:08,459 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-2] Native decoder process on GPU 1 is starting
2019-04-01 17:56:08,459 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-3] Native decoder process on GPU 2 is starting
2019-04-01 17:56:08,459 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-4] Native decoder process on GPU 3 is starting
2019-04-01 17:56:41,151 ERROR eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-4] Native decoder process on GPU 3 failed to start
java.io.IOException: Failed to start neural decoder, received: null
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl.init(PythonDecoderImpl.java:123)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.start(PythonDecoderImpl.java:94)
        at eu.modernmt.decoder.neural.execution.impl.PythonDecoderImpl$Builder.startOnGPU(PythonDecoderImpl.java:61)
        at eu.modernmt.decoder.neural.execution.impl.Handler.restart(Handler.java:55)
        at eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl$Initializer.run(DecoderQueueImpl.java:196)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-01 17:56:41,155 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2019-04-01 17:56:41,168 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2019-04-01 17:56:41,169 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
        at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
        at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
```

**Comment by mtresearcher** [comment] 2019-04-01 18:46
#451

**Comment by mtresearcher** [comment] 2019-04-01 19:24
If I modify `engines/train-full-en-es/engine.xconf` and add 
`<decoder enabled="false"/>`
MMT engine starts now but this is not what I really want, I want MMT to run on GPU (preferably multi-gpu).
Did you guys run the current version of MMT successfully on a multi-gpu environment?

**Comment by mtresearcher** [comment] 2019-04-01 22:31
Continuing this thread: now that with CPU the `./mmt start` works, I ran into another problem. 
I am getting a "Language pair not supported" error while translating. 

```
ubuntu@38c7e6454d7e:~/mmt$ ./mmt translate -e multilingual -s en -t es --context background < test

ModernMT Translate command line
>> No context provided.

>
ERROR Unexpected exception: HTTP request "http://localhost:8045/translate?q=hello%2C+how+are+you%3F&source=en&target=es&priority=background" failed with code 400: (UnsupportedLanguageException) Language pair not supported: en > es
Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 423, in main_translate
    translator.run(sys.stdin, sys.stdout)
  File "/home/ubuntu/mmt/cli/translators.py", line 345, in run
    translation = self._engine.translate_text(line)
  File "/home/ubuntu/mmt/cli/translators.py", line 170, in translate_text
    raise TranslateError(e.message)
cli.translators.TranslateError: HTTP request "http://localhost:8045/translate?q=hello%2C+how+are+you%3F&source=en&target=es&priority=background" failed with code 400: (UnsupportedLanguageException) Language pair not supported: en > es
```

```
ubuntu@38c7e6454d7e:~/mmt$ curl -X GET http://localhost:8045/translate -d "source=en" -d "target=es" -d "priority=background" -d "q=Hello"
{"status":400,"error":{"type":"UnsupportedLanguageException","message":"Language pair not supported: en > es"}}
```

```
ubuntu@38c7e6454d7e:~/mmt$ cat engines/multilingual/engine.xconf
<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <engine type="neural" source-language="en" target-language="es" name="multilingual">
      <languages>
      <pair source="en" target="es"/>
      </languages>
      <decoder enabled="false" gpus="none" threads="16"/>
      <aligner enabled="false" />
   </engine>
</node>
```

```
ubuntu@38c7e6454d7e:~/mmt$ cat engines/multilingual/models/decoder/model.conf
[models]
en__es = en__es/
```

```
ubuntu@38c7e6454d7e:~/mmt$ ./mmt status
[Engine: "multilingual"]
    REST API:   running - 8045/translate
    Cluster:    running - port 5016
    Datastream: running - localhost:9092
    Database:   running - localhost:9042
```

**Comment by nicolabertoldi** [comment] 2019-04-02 08:19
Hi @mtresearcher ,

in the engine.xconf this line disables the decoder
```<decoder enabled="false" gpus="none" threads="16"/>```
This is why any language is not recognized.


The correct engine.xconf for a multilingual engine should appear like the following:
```
<node xsi:schemaLocation="http://www.modernmt.eu/schema/config mmt-config-1.0.xsd"
      xmlns="http://www.modernmt.eu/schema/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <engine type="neural">
      <languages>
      <pair source="en" target="es"/>
      <pair source="en" target="it"/>
      </languages>
      <decoder threads="16"/>
      <aligner enabled="false" />
   </engine>
</node>
```

A few comments:
- for a multilingual engine you have to specify all languages with the tag ``languages``, and you can remove the parameters ``source-language`` and ``target-language`` in the tag `` engine``
- our software does not work on cpu (at the moment), so you have to specify at least one gpu in the tag ``decoder``; if you do not specify anything all available gpus are used



By the way your original problem has a different reason. TO understand which the real problem is, please comment the following lines 41 and 42
https://github.com/modernmt/MMT/blob/master/src/decoder-neural/src/main/python/__main__.py#L41
so that you can catch the error

please, report the error you get, and we will support you further.

**Comment by nicolabertoldi** [comment] 2019-04-02 08:28
To understand which the real problem is, please do the following:
- comment the following lines 41 and 42
https://github.com/modernmt/MMT/blob/master/src/decoder-neural/src/main/python/__main__.py#L41


- run the following command 
``` python src/decoder-neural/src/main/python/__main__.py    engines/ENGINE/models/decoder/```
where ``ENGINE`` is the name of your engine.


please, report the error you get, and we will support you further.

**Comment by mtresearcher** [comment] 2019-04-02 14:55
I didn't have the installation from the source code. I was using the docker image directly. I installed MMT from source to change the `__main__.py` file, copied the engine directory and ran the script, this is the output:

```
ubuntu@ip-172-31-10-210:~/git/ModernMT$ python src/decoder-neural/src/main/python/__main__.py engines/train-full-en-es/models/decoder/
/home/ubuntu/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "src/decoder-neural/src/main/python/__main__.py", line 78, in <module>
    run_main()
  File "src/decoder-neural/src/main/python/__main__.py", line 69, in run_main
    decoder = TransformerDecoder(args.gpu, checkpoints, config=config)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 140, in __init__
    self._warmup()
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 264, in _warmup
    self._reset_model(random_checkpoint)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 204, in _reset_model
    self._restorer.restore(self._session, checkpoint)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/checkpoint.py", line 286, in restore
    session.run(self._model_assign_op, feed_dict=self._feeds[checkpoint])
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512] rhs shape= [1024]
	 [[Node: Assign_156 = Assign[T=DT_FLOAT, _class=["loc:@Assign_479"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/transformer/body/encoder/layer_0/ffn/layer_prepostprocess/layer_norm/layer_norm_bias/Adam, _arg_Placeholder_160_0_66)]]

Caused by op u'Assign_156', defined at:
  File "src/decoder-neural/src/main/python/__main__.py", line 78, in <module>
    run_main()
  File "src/decoder-neural/src/main/python/__main__.py", line 69, in run_main
    decoder = TransformerDecoder(args.gpu, checkpoints, config=config)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 140, in __init__
    self._warmup()
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 264, in _warmup
    self._reset_model(random_checkpoint)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/transformer.py", line 204, in _reset_model
    self._restorer.restore(self._session, checkpoint)
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/checkpoint.py", line 284, in restore
    self._init()
  File "/home/ubuntu/git/ModernMT/src/decoder-neural/src/main/python/nmmt/checkpoint.py", line 272, in _init
    to_model_assign_ops.append(state_ops.assign(global_variable, placeholder))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512] rhs shape= [1024]
	 [[Node: Assign_156 = Assign[T=DT_FLOAT, _class=["loc:@Assign_479"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/transformer/body/encoder/layer_0/ffn/layer_prepostprocess/layer_norm/layer_norm_bias/Adam, _arg_Placeholder_160_0_66)]]
```

PS: I haven't changed any model parameters, its the same as in training.

**Comment by nicolabertoldi** [comment] 2019-04-02 15:36
It seems that there is an inconsistency in the model size (for instance, transformer_big vs transformer_base).
Have you trained a big or base model?
Which is the size of the model files in engines/train-full-en-es/models/decoder/?
Could you please report the content of hparams?

**Comment by mtresearcher** [comment] 2019-04-02 15:38
I tried transformer_big

**Comment by mtresearcher** [comment] 2019-04-02 15:40
```
"activation_dtype": "float32",
"attention_dropout": 0.1,
"attention_dropout_broadcast_dims": "",
"attention_key_channels": 0,
"attention_value_channels": 0,
"batch_size": 3072,
"clip_grad_norm": 0.0,
"compress_steps": 0,
"conv_first_kernel": 3,
"daisy_chain_variables": true,
"data_dir": "/home/ubuntu/mmt/runtime/train-full-en-es/tmp/training/neural_train_data/data",
"dropout": 0.2,
"eval_drop_long_sequences": false,
"eval_run_autoregressive": false,
"eval_steps": 100,
"factored_logits": false,
"ffn_layer": "dense_relu_dense",
"filter_size": 2048,
"force_full_predict": false,
"grad_noise_scale": 0.0,
"hidden_size": 512,
"initializer": "uniform_unit_scaling",
"initializer_gain": 1.0,
"input_modalities": "default",
"kernel_height": 3,
"kernel_width": 1,
"label_smoothing": 0.1,
"layer_postprocess_sequence": "da",
"layer_prepostprocess_dropout": 0.1,
"layer_prepostprocess_dropout_broadcast_dims": "",
"layer_preprocess_sequence": "n",
"learning_rate": 0.2,
"learning_rate_constant": 2.0,
"learning_rate_cosine_cycle_steps": 250000,
"learning_rate_decay_rate": 1.0,
"learning_rate_decay_scheme": "noam",
"learning_rate_decay_staircase": false,
"learning_rate_decay_steps": 5000,
"learning_rate_minimum": null,
"learning_rate_schedule": "constant*linear_warmup*rsqrt_decay*rsqrt_hidden_size",
"learning_rate_warmup_steps": 8000,
"length_bucket_step": 1.1,
"max_input_seq_length": 0,
"max_length": 256,
"max_relative_position": 0,
"max_target_seq_length": 0,
"min_length": 0,
"min_length_bucket": 8,
"model_dir": "/home/ubuntu/mmt/runtime/train-full-en-es/tmp/training/neural_model",
"moe_hidden_sizes": "2048",
"moe_k": 2,
"moe_loss_coef": 0.001,
"moe_num_experts": 16,
"moe_overhead_eval": 2.0,
"moe_overhead_train": 1.0,
"multiply_embedding_mode": "sqrt_depth",
"nbr_decoder_problems": 1,
"no_data_parallelism": false,
"norm_epsilon": 1e-06,
"norm_type": "layer",
"num_decoder_layers": 0,
"num_encoder_layers": 0,
"num_heads": 8,
"num_hidden_layers": 6,
"optimizer": "Adam",
"optimizer_adafactor_beta1": 0.0,
"optimizer_adafactor_beta2": 0.999,
"optimizer_adafactor_clipping_threshold": 1.0,
"optimizer_adafactor_decay_type": "pow",
"optimizer_adafactor_factored": true,
"optimizer_adafactor_memory_exponent": 0.8,
"optimizer_adafactor_multiply_by_parameter_scale": true,
"optimizer_adam_beta1": 0.9,
"optimizer_adam_beta2": 0.997,
"optimizer_adam_epsilon": 1e-09,
"optimizer_momentum_momentum": 0.9,
"optimizer_momentum_nesterov": false,
"parameter_attention_key_channels": 0,
"parameter_attention_value_channels": 0,
"pos": "timing",
"prepend_mode": "none",
"proximity_bias": false,
"relu_dropout": 0.1,
"relu_dropout_broadcast_dims": "",
"sampling_method": "argmax",
"sampling_temp": 1.0,
"scheduled_sampling_gold_mixin_prob": 0.5,
"scheduled_sampling_prob": 0.0,
"scheduled_sampling_warmup_steps": 50000,
"self_attention_type": "dot_product",
"shared_embedding_and_softmax_weights": true,
"split_to_length": 0,
"summarize_grads": false,
"summarize_vars": false,
"symbol_dropout": 0.0,
"symbol_modality_num_shards": 16,
"symbol_modality_skip_top": false,
"target_modality": "default",
"train_steps": 100000000,
"use_fixed_batch_size": false,
"use_pad_remover": true,
"weight_decay": 0.0,
"weight_dtype": "float32",
"weight_noise": 0.0
```

**Comment by nicolabertoldi** [comment] 2019-04-02 15:47
Hi @mtresearcher 

actually your hparams    corrresponds to a transformer_base and not to a transformer_big.
I suspect that at same time the original hparams for the big was overwritten.

Could you please verify that the file of your model is around 2.5Gb (the expected size of the big)

**Comment by mtresearcher** [comment] 2019-04-02 15:48
Yes, it is indeed 2.4G
2.4G	model-avg-467000.data-00000-of-00001

**Comment by mtresearcher** [comment] 2019-04-02 15:50
Could you paste me the params for transformer_big?

**Comment by nicolabertoldi** [comment] 2019-04-02 15:51
Ok

so to avoid you retrain the system

you can train a toy model with transformer big in order to get the correct hparams file
then copy this new hparams into engines/train-full-en-es/models/decoder/ overwriting the wrong one

**Comment by mtresearcher** [comment] 2019-04-02 15:51
oh awesome. will do! 
I'll update you in a few minutes.

**Comment by mtresearcher** [comment] 2019-04-02 16:39
Now, the python command seems to work. I can see "READY" in the output. 
Next step I did was to try start the MMT server but it failed saying:
```
Starting MMT engine 'multilingual'... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/multilingual/logs/node.log
Traceback (most recent call last):
  File "./mmt", line 612, in <module>
    main()
  File "./mmt", line 558, in main
    actions[command](args)
  File "./mmt", line 193, in main_start
    log_file=args.log_file)
  File "/home/ubuntu/mmt/cli/mmt/cluster.py", line 314, in start
    raise Exception('failed to start node, check log file for more details: %s' % self._log_file)
Exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/multilingual/logs/node.log
```

**Comment by nicolabertoldi** [comment] 2019-04-02 16:43
Now your model and hparams is fine

To make the full system work you have to remove the comments I suggested to insert here
https://github.com/modernmt/MMT/blob/master/src/decoder-neural/src/main/python/__main__.py#L41

if this not resolve, please report the content of node.log

**Comment by mtresearcher** [comment] 2019-04-02 16:50
How much time does it take to start the engine if model is transformer_big?

**Comment by nicolabertoldi** [comment] 2019-04-02 16:56
more or less 1 minute


Nicola


-- 
--
Le informazioni contenute nella presente comunicazione sono di natura privata e come tali sono da considerarsi riservate ed indirizzate esclusivamente ai destinatari indicati e per le finalità strettamente legate al relativo contenuto. Se avete ricevuto questo messaggio per errore, vi preghiamo di eliminarlo e di inviare una comunicazione all’indirizzo e-mail del mittente.
--
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. If you received this in error, please contact the sender and delete the material.

**Comment by mtresearcher** [comment] 2019-04-02 17:00
`./mmt start -e multilingual` doesn't seem to work for me. If I copy "multilingual" directory to another directory "xxx" and try starting the xxx engine... the `./mmt start` gets stuck for a long time.

**Comment by mtresearcher** [comment] 2019-04-02 17:02
node.log is not even created for me.

**Comment by mtresearcher** [comment] 2019-04-02 17:10
I created a new docker container and now it seems to work. There were some defunct jobs that were created in the previous container so created a new one.

**Comment by nicolabertoldi** [comment] 2019-04-02 17:14
very good!
If you confirm that the problem is solved, let me know so that I can close this issue.

I would suggest to restart the docker every time you will experience some un-explicable problems.

**Comment by mtresearcher** [comment] 2019-04-02 17:22
You can go ahead and close this issue.
Outcome of this issue can be compiled as ... When MMT packs the model it
looks at hprams-set string and not at the hparams.json for correct
parameters. MMT should have even allowed me to run the training in the
first place if the hparam-set string didn't match. Could you add this in
your backlog?

**Comment by nicolabertoldi** [comment] 2019-04-02 17:26
could you please write me the exact sequence of commands you run which causes your problem
so that I try to reproduce it?

**Comment by mtresearcher** [comment] 2019-04-02 18:05
I ran this command in a screen:
`./mmt create en es data/train -e train-full-en-es --hparams transformer_big`
then training continued several days, but the screen was dead. I couldn't do Ctrl+C to stop the training so I killed `t2t-trainer` which didn't trigger packing of model. 
So, I resume the training with 
`./mmt create en es data/train -e train-full-en-es -r` 
The training started (I don't know why) even though I forgot about the hparams flag. 
Then, I did Ctrl+C which triggered the packing of model but with transformer_base params. 
What I am saying is, MMT should look at the hparams.json than at haparams flag to continue training and packing.

**Comment by nicolabertoldi** [comment] 2019-04-02 20:14
Hi @mtresearcher 
thank you for this info,
I will retry these steps and check what is wrong

For the future, if you lose the bash (or the screen) running the training, the correct way to stop the training step and finalise the engine with the packing step is to follow my instructions in this comment
https://github.com/modernmt/MMT/issues/396#issuecomment-437847220

**Comment by mtresearcher** [comment] 2019-04-02 20:50
Thanks! that's a very useful thread. It would be good to have this comment in the documentation.

**Comment by nicolabertoldi** [comment] 2019-04-03 21:22
We will update the documentation as soon as possible.

I am closing the issue, but if you still have such problems please don't hesitate to re-open it!

**Closed by nicolabertoldi** 2019-04-03 21:22 UTC
