### ISSUE TITLE
Some text is completely ignored by MMT when translating !

### ISSUE THREAD

**Issue by philippehenri** [ModernMT/MMT#411] opened 2018-10-25 08:27 UTC
Hello,

I was trying to send two sentences for translation, and I noticed that only one sentence gets translated in some cases and the other is ignored? Sometimes the first sentence is translated, sometimes the second one... sometimes both.

1/ Example, i try to translate these two sentences:

Lymfadenitis of lymfeklierontsteking is een aandoening waarbij je lymfklieren ontstoken raken. Wanneer de lymfeklieren in de buikholte, in het bijzonder het mesenterium (de plooi van het buikvlies die over de darmen hangt), dan wordt het 'mesenteriële adenitis' genoemd.

I query the api:

http://...:8045/translate?source=nl&target=fr&q=Lymfadenitis+of+lymfeklierontsteking+is+een+aandoening+waarbij+je+lymfklieren+ontstoken+raken.+Wanneer+de+lymfeklieren+in+de+buikholte%2C+in+het+bijzonder+het+mesenterium+%28de+plooi+van+het+buikvlies+die+over+de+darmen+hangt%29%2C+dan+wordt+het+%27mesenteri%C3%ABle+adenitis%27+genoemd.

MMT translates only the SECOND sentence (starting with “Wanneer…”), the result is (note the parenthesis that appear only in the second sentence):

Si les ganglions lymphatiques dans la cavité abdominale, en particulier le mésentérium (le pli de la membrane abdominale qui traverse les intestins), on appelle "adénopathie mésentérique".

2/ BUT If i add for example “xx” in front of the whole block: “xx Lymfadenitis of lymfeklierontsteking is een aandoening waarbij je lymfklieren ….” then only the FIRST sentence gets translated: 

“xx La lymphadénite ou l'inflammation des ganglions lymphatiques est une affection dans laquelle les ganglions lymphatiques s'enflamment.”

3/ Now, it seems to depends on what is added, example if i add “Wanneer” instead of “xx” then BOTH sentences get translated : 

“Lorsque la Lympfadénite ou l'inflammation des ganglions lymphatiques est une affection dans laquelle les ganglions lymphatiques s'enflamment. Lorsque les ganglions lymphatiques dans la cavité abdominale, en particulier le mésentérium (le pli de la membrane abdominale qui traverse les intestins), on appelle "l'adénopathie mésentérique".”

what is the problem? (i did other multi sentences tests and didn't notice such problems)

thanks

**Comment by LoekvanKooten** [comment] 2018-10-25 08:34
The CAT I programmed myself splits segments with multiple sentences so that they can be fed one by one. Later I combine them again in the same segment. This gives far better results (it's a well-known fact that NMT chokes on longer sentences anyway).

**Comment by philippehenri** [comment] 2018-10-25 08:38
ok but it seems to be clearly a bug here as sometimes it works, sometimes not. seems very random... :(

**Comment by EtienneAb3d** [comment] 2018-10-25 08:44
It's not a bug. MMT is a learning tool. It does what your are training it to do. If you are training it to translate single sentences, and then send it multiple sentences at once, it's just not coherent. 
;-)

**Comment by philippehenri** [comment] 2018-10-25 09:02
well if it was the case, then i am wondering why i get 3 different behaviours by changing a single word (see my 3 examples), with the same training set... and i have plenty of examples when it works perfectly. I was therefore suggesting that this case is highlighting a potential problem...

**Comment by EtienneAb3d** [comment] 2018-10-25 09:10
When you send to a learning system something it wasn't trained for, the result is quite random. A very small difference in the entry can produce a high difference on the output. The "normal" (trained) behaviour, in this case, would be to translate only the first sentence, and stop on the first final point. But, then you send it more elements. The network is then confused on what should be done (=the probability calculation is not clearly for one option or an other). If it's computation tells it the end is reached, it stops. If it's computation leave a small possibility for something more, it processes more. This is just on the line for a small probability on one choice or the other.

**Comment by philippehenri** [comment] 2018-10-25 16:12
ok well noted, thanks to all for the comments.

**Comment by LoekvanKooten** [comment] 2018-10-29 17:11
Where exactly is this logged? As runtime/engdut/logs is not updated.

**Comment by davidecaroselli** [comment] 2018-10-30 10:15
`runtime/engdut/logs/node.log` is the right path, **if** you're running an engine named `engdut`. Otherwise, look for the right folder in the `runtime` path

**Comment by LoekvanKooten** [comment] 2018-10-30 10:45
I've looked there and that log is indeed updated (not if you've changed/delete the file manually while mmt is running - after that a restart is needed), but except for the sentences it gets fed and feeds, -v 2 gives me no more info. I was expecting something on word level?

**Comment by LoekvanKooten** [comment] 2018-11-01 10:11
@davidecaroselli /bump

**Comment by nicolabertoldi** [comment] 2018-11-12 09:50
The issue related to the "ignored" text is better handled and explained in #416.

Hence, I am closing this issue.

Please feel free to re-open if you still want to discuss here.

**Comment by EtienneAb3d** [comment] 2018-11-12 09:56
As I understand it, I'm not sure there is really a link between these 2 questions, except the fact that the output is sorter than expected.

**Comment by nicolabertoldi** [comment] 2018-11-12 10:14
@EtienneAb3d, for the future please reopen the issue if you want to comment furthter on a specific issue

**Comment by nicolabertoldi** [comment] 2018-11-12 10:28
Text can be ignored for some reasons:

1. The decoding is truncated on the right side, because there is a limited amount of output bpe subtokens, which can be produced. This scenario is better explained in #416.
2. The input contains more sentences (separated by strong punctuation). In this case, the strong punctuation is a strong trigger to consider the translation completed. Moreover as @EtienneAb3d pointed out, the system is usually trained on single sentences, so it can have difficulties to translated not-coherent inputs (i.e. including more sentences). So it not strange that only the first sentence(s) are translated. It is more hard to explain why sometimes the first sentence(s) are not translated, which can be probably related to the attention model mechanism, which let the decoder focus on some parts of the input and not to others.
3. Only small portions of the input are not translated. This is mainly due to the fact that the transformer can choose to not focus on some portions of the input; it is not obliged to "cover" all the input.

**Comment by davidecaroselli** [comment] 2018-12-03 12:17
Thanks to all for the discussion, I'm closing this issue for now but as always feel free to re-open it if for further discussions

**Closed by davidecaroselli** 2018-12-03 12:17 UTC

**Comment by lkluo** [comment] 2019-06-04 04:47
What if we feed a paragraph (containing a few sentences) as a sequence into training? By doing so the model shall know how to translate a paragraph during decoding. The only thing matters is the memory.  Why I raise this is because in reality, a sentence from one language can be translated into two or more in another language (of cause, translated by human translators).

**Comment by EtienneAb3d** [comment] 2019-06-04 05:17
Certainly there isn't any problem to train with entries containing several sentences. But, keep in mind that the model is really efficient when trained on the same kind of data as the one you send at translation time. 
On the translation side, managing several sentences in your workflow may bring you with some difficulties. 
On the training side, it could be a bit hard to produce a large set of pertinent training pairs with several (millions?) sentences. It's not really pertinent to just merge N random pairs without taking into account the fact that these pairs should really linguistically be put together.

**Comment by lkluo** [comment] 2019-06-04 06:00
@EtienneAb3d: I agree with you. One sentence shall align to one sentence for NMT model. Sometimes, it can be difficult to alignment sentences when collecting training data. As I mentioned earlier, it is common for some language pairs, that one source sentence can be translated into more than one  target sentences. In order to align with one-sentence-to-one-sentence criterion, it might need human work (of course, some algorithm may be design for auto-alignment). Anyhow, it is the easiest way to feed multiple-source multiple-target pairs into model training.

**Comment by EtienneAb3d** [comment] 2019-06-04 06:03
Yes. But this is not a problem with MMT, it's a problem concerning your pre/post-processing. It's up to you to provide MMT with aligned N-M sentences if you want. It won't complain about this.
