### ISSUE TITLE
Error when tuning a neural engine

### ISSUE THREAD

**Issue by aoliverg** [ModernMT/MMT#373] opened 2018-05-14 10:33 UTC
Hello:

After training a neural engine I try to tune it and I get the following error:

./mmt tune -e UE1-neural-es-ca

============ TUNING STARTED ============

ENGINE:  UE1-neural-es-ca
CORPORA: /home2/aoliverg/ModernMT-24/engines/UE1-neural-es-ca/data/dev (1 documents)
LANGS:   es > ca

INFO: (1 of 2) Corpora pre-processing...                               DONE (in 0s)
INFO: (2 of 2) Tuning...                                               DONE (in 0s)

ERROR Unexpected exception:
	TypeError("'NoneType' object has no attribute '__getitem__'",)
Traceback (most recent call last):
  File "./mmt", line 846, in <module>
    main()
  File "./mmt", line 792, in main
    actions[command](args)
  File "./mmt", line 345, in main_tune
    tuning.start(node, corpora, debug=args.debug)
  File "/home2/aoliverg/ModernMT-24/cli/training.py", line 148, in start
    self._start_fn(node, corpora, self, debug)
  File "/home2/aoliverg/ModernMT-24/cli/training.py", line 109, in <lambda>
    max_lines=max_lines, lr_delta=lr_delta, max_epochs=max_epochs, gpus=gpus), False)
  File "/home2/aoliverg/ModernMT-24/cli/mmt/cluster.py", line 576, in nmt_tune
    max_epochs=max_epochs, log_file=log_file, gpus=gpus)
  File "/home2/aoliverg/ModernMT-24/cli/mmt/neural.py", line 299, in tune
    decoder = nmmt.NMTDecoder(model_folder, gpus[0])
TypeError: 'NoneType' object has no attribute '__getitem__'

If I specify the gpuid in the command line I got the same error.

Do you know how can I fix this problem?

Thank you

Antoni

**Comment by davidecaroselli** [comment] 2018-05-14 11:32
Hi @aoliverg 

luckily, the good news is you don't have to tune a neural engine: tuning is an operation needed only for phrase-based engines. I will take care of changing the UI in order to make this clear if an user tries to run tuning on a Neural engine.

By the way, is this a duplicate of #369 of are these two different scenarios?

Best,
Davide

**Comment by aoliverg** [comment] 2018-05-14 13:27
Hello:

Thank you for the reply. I was confused and though I should also tune neural engines. The issu #369 is different. I will add some information in the other issue.

Antoni

**Closed** 2018-05-14 14:31 UTC
Labels: enhancement
