### ISSUE TITLE
Bug in the live-tuning when using 2 variants of the same language

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/MMT#442] opened 2019-01-31 09:09 UTC
Suppose I add a pair fr-FR/fr-CA to a memory. 
When I'm translating a sentence from fr-FR to fr-CA, it takes a live-tuning pair being twice the SRC segment, thus fr-FR/fr-FR.
I don't know if the problem is during the add step, or the translation step.

**Comment by davidecaroselli** [comment] 2019-01-31 13:22
ModernMT is not built to support same language "translation", so the memory won't recognize "fr-FR" and "fr-CA" as two different languages, and it will consider them both as "fr". It handles language variations, giving higher score with suggestions with the same language variation, but it indexes them both in the same "storage" of "fr".

**Comment by EtienneAb3d** [comment] 2019-02-01 07:09
Is there a simple way to change this ? 
The alternative is to use a bad language, like "en" in place of "fr", but it will be a bit complex to manage this kind of replacement in a lot of different cases (for the moment, I only have "fr").

**Comment by EtienneAb3d** [comment] 2019-02-01 09:03
For a very short consideration on my already trained model: is there a way to change the languages of an existing model ? In this case, to turn "fr-CA" to "en" ? In my current process, I need the live-adaptation. This would enable me to use the model without retraining it.

**Comment by davidecaroselli** [comment] 2019-02-01 11:48
> The alternative is to use a bad language, like "en" in place of "fr"

The problem with this approach is that ModernMT will treat "fr" like english: the tokenization will be in English, this will produce a worst output and, more important a tokenization that is not coherent with the one used for the training.

> is there a way to change the languages of an existing model?

Yes, the languages are declared in the `decoder/model.conf` file. Just change the line `en__it = en__it/` line into `fr__en = en__it/` and ModernMT will use the same model for fr > en instead of en > it for example.

So how can you achieve your goal? I think the best option for you is to fork ModernMT on your github and apply the change on the Memory index algorithm (I can help you with that). The problem is that you will lose the ability to mix different language variations for the adaptation: i.e. uploading suggestions for fr-CA and fr-FR will result in two different languages, not sharing anything (just like, le's say, "fr" and "ru") - when translating en > fr-CA you won't be able to adapt using suggestions from en > fr-FR.

**Comment by EtienneAb3d** [comment] 2019-02-01 12:38
Changing the model.conf, I got this:
Language direction 'en -> fr' is not supported Translate
My line is:
en__fr = fr-CA__fr-FR/

**Comment by EtienneAb3d** [comment] 2019-02-01 12:51
Got it !!
I set "en-GB" in both **model.conf** and **engine.xconf**, and it works !
Thanks !

**Comment by EtienneAb3d** [comment] 2019-02-01 13:08
Here is what I'm currently experimenting (only in french in this very first version):
http://neurospell.com/

**Comment by mzeidhassan** [comment] 2019-02-07 19:41
Just a follow-up question here for @davidecaroselli on changing the language direction manually.

Does this mean that by doing this, you can basically use the same engine (EN-FR) for (FR-EN) translation? Am I getting this correctly or is there something I missed? 

If my assumption is true, would this be the same as training a target->source engine, (FR-EN) in our scenario, from scratch?

**Comment by EtienneAb3d** [comment] 2019-02-08 12:01
The trained model is always the same, thus always from source to target. The modification is just a renaming of the parameters you use to call the model with something to translate.

**Comment by davidecaroselli** [comment] 2019-02-08 17:03
@mzeidhassan just like @EtienneAb3d said: the neural network is **mono-directional**, and won't change if you change the meta-data in `model.conf`. If you trained an engine `EN > FR`, you won't be able to use it also for `FR > EN`.

I'm closing this issue for now, but as always feel free to re-open it if you have any other questions!

**Closed by davidecaroselli** 2019-02-08 17:03 UTC
